#!/bin/csh -f

#######################################################################################
# This script is the driver for QUICKPLOT plots in LANDSCAPE mode.
# To produce a list of LANDSCAPE plots, simply issue the following 3 commands:
#    (1)  landscape.script -v -list -source $SOURCE > & dummy
#    (2)  grep "plot ==" dummy | tee landscape.list
#    (3)  /bin/rm dummy
# where $SOURCE is an OPTIONAL valid SOURCE directory containing a HISTORY.rc
#######################################################################################

set plots = ""
set plots = `echo $plots` # To remove blanks

set LIST  = FALSE


setenv ORIENTATION LANDSCAPE
if ( ! $?LONSENV ) then
  setenv LONSENV "0 360"
endif
if ( ! $?LATSENV ) then
  setenv LATSENV "-90 90"
endif

# Set Defaults
# ------------
set    batch = " "
set    debug = "no_debug"
set    expid = '$EXPID'
set   source = '$SOURCE'
set     plot = 'plot'
set   output = '$OUTPUT'
set geosutil = '$GEOSUTIL'
set  seasons = '$SEASON'
set    grads = "grads"

if(! $?CMPEXP ) setenv CMPEXP NULL

@ nmax = $#argv

# Parse command line
# ------------------
@       n  = 1
while( $n <= $nmax )

       if( "$argv[$n]" == "-list" ) then
               set LIST = TRUE
       endif

       if( "$argv[$n]" == "-v" ) then
               set echo
       endif

       if( "$argv[$n]" == "-expid" ) then
                    @ n = $n + 1
             set expid  = $argv[$n]
       endif
       if( "$argv[$n]" == "-source" ) then
                    @ n = $n + 1
           set source   = $argv[$n]
       endif
       if( "$argv[$n]" == "-plot"   ) then
                    @ n = $n + 1
             set plot   = $argv[$n]
       endif
       if( "$argv[$n]" == "-output" ) then
                    @ n = $n + 1
             set output = $argv[$n]
       endif
       if( "$argv[$n]" == "-geosutil" ) then
                    @ n = $n + 1
             set geosutil = $argv[$n]
       endif
       if( "$argv[$n]" == "-debug"   ) then
             set debug = "debug"
       endif
       if( "$argv[$n]" == "-grads"   ) then
                    @ n = $n + 1
             set grads = $argv[$n]
       endif
       if( "$argv[$n]" == "-zlog"   ) then
                    @ n = $n + 1
             set zlog = $argv[$n]
       endif
       if( "$argv[$n]" == "-batch"   ) then
             set batch = "-b"
       endif
       if( "$argv[$n]" == "-season"  ) then
                    @ n = $n + 1
                                      set seasons = ""
                                      set next   = $argv[$n]
                                      set bit    = `echo $next | cut -c1-1`
                                      while( "$bit" != "-" )
                                         set seasons = `echo $seasons $next`
                                          @   n  = $n + 1
                                         if( $n <= $nmax ) then
                                             set next = $argv[$n]
                                             set bit  = `echo $next | cut -c1-1`
                                         else
                                             set bit  = "-"
                                         endif
                                      end
                                             @ n = $n - 1
       endif
     @ n = $n + 1
end

if( -e $source/.HOMDIR ) then
    set homdir = `cat $source/.HOMDIR`
else
    set homdir = $source  
endif


if( $LIST == FALSE ) then
    echo "Landscape Script"
    echo "----------------"
    echo "   expid: $expid"
    echo "  source: $source"
    echo "  homdir: $homdir"
    echo "    plot: $plot"
    echo "  output: $output"
    echo "geosutil: $geosutil"
    echo "   debug: $debug"
    echo "  season: $seasons"
endif

set  plot_type = `echo $plot | cut -c2-5`
if( $plot_type == 'quad' ) then
    setenv PLOT_QUAD true
else
    setenv PLOT_QUAD false
endif

#######################################################################################
#                    Compute Landscape PLOTS for SOURCE Experiment
#######################################################################################

     set plotname = ${ORIENTATION}
     @ n = 1


# Prognostics: Loop over Variables for Zonal Mean Comparisons
# -----------------------------------------------------------
     set EXPORTS = `echo U   V   T   RH2  `
     set GCS     = `echo DYN DYN DYN MOIST`
     @ k = 0
     foreach EXPORT ($EXPORTS)
       @ k = $k + 1
       set GC = $GCS[$k]
       if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/zcmp1/progz1 $EXPORT $GC $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end

     set EXPORTS = `echo ZLE SLP U   V   T   Q     RH2  `
     set GCS     = `echo DYN DYN DYN DYN DYN MOIST MOIST`
     @ k = 0
     foreach EXPORT ($EXPORTS)
       @ k = $k + 1
       set GC = $GCS[$k]
       if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/lcmp/lcmp1 $EXPORT $GC $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end


# Time-Series
# -----------
# Time Series
# -----------
    if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/tseries/aerosols   $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/tseries/ps         $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/tseries/pme        $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/tseries/tpw        $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/tseries/rad        $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/tseries/ke         $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/zcmp1/vortex U DYN $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/zcmp1/qbo    U DYN $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Quadratics
# ----------
                    set CMPEXPS = `echo $CMPEXP`
if( $LIST == TRUE ) set CMPEXPS = `echo $CMPEXPS $VERIFICATION/MERRA_MEANS:A $VERIFICATION/MERRA2_MEANS:A`

foreach exp ($CMPEXPS)
if( $exp != NULL ) then
     set INFO  = "-CMPEXP $exp NULL -SEASON $seasons  -OUTPUT $output -DEBUG $debug "
     if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/quad/zquad -EXPID $expid -EXPORT1     U:DYN -EXPORT2     U:DYN $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/quad/zquad -EXPID $expid -EXPORT1     V:DYN -EXPORT2     V:DYN $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/quad/zquad -EXPID $expid -EXPORT1     T:DYN -EXPORT2     T:DYN $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/quad/zquad -EXPID $expid -EXPORT1   ZLE:DYN -EXPORT2   ZLE:DYN $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/quad/zquad -EXPID $expid -EXPORT1 OMEGA:DYN -EXPORT2 OMEGA:DYN $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/quad/zquad -EXPID $expid -EXPORT1   Q:MOIST -EXPORT2   Q:MOIST $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/quad/zquad -EXPID $expid -EXPORT1     U:DYN -EXPORT2     V:DYN $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/quad/zquad -EXPID $expid -EXPORT1     V:DYN -EXPORT2     T:DYN $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/quad/zquad -EXPID $expid -EXPORT1     V:DYN -EXPORT2   Q:MOIST $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/quad/zquad -EXPID $expid -EXPORT1 OMEGA:DYN -EXPORT2     T:DYN $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/quad/zquad -EXPID $expid -EXPORT1 OMEGA:DYN -EXPORT2   Q:MOIST $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     if( $plot == $plotname.$n ) $grads $batch -l -c "run $GEOSUTIL/plots/quad/zquad -EXPID $expid -EXPORT1    KE:DYN -EXPORT2    KE:DYN $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
endif
end


# Energy
# ----------
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEDYN:DYN KEPHY:DYN KEANA:DYN   -NAME DKEDT   -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEGEN:DYN                                     -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEDYN:DYN                                     -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEPG:DYN                                      -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEDP:DYN                                      -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEADV:DYN                                     -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEHOT:DYN                                     -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEGEN:DYN PEDYN:DYN CONVCPT:DYN -NAME TEFIXER -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DKERESIN:DYN                                  -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DKERESPG:DYN                                  -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEREMAP:DYN                                   -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEDYN:DYN KEPHY:DYN KEANA:DYN   -NAME DKEDT   -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT TEDYN:DYN TEPHY:DYN TEANA:DYN   -NAME DTEDT   -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEDYN:DYN KEPHY:DYN KEANA:DYN TEDYN:DYN TEPHY:DYN TEANA:DYN -NAME DKETEDT -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    TEDYN:DYN         -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    TEPHY:DYN         -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    TEANA:DYN         -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEDYN:DYN TEDYN:DYN -NAME KETEDYN -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEPHY:DYN TEPHY:DYN -NAME KETEPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEANA:DYN TEANA:DYN -NAME KETEANA -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  KEGEN:DYN CONVPHI:DYN CONVKE:DYN                     -NAME KETEDYN2 -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  KEGEN:DYN CONVPHI:DYN CONVKE:DYN KEDYN:DYN TEDYN:DYN -NAME KETEDYN3 -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    KEPHY:DYN         -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    KEANA:DYN         -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    KEGWD:GWD         -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    KEORO:GWD         -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    KERAY:GWD         -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    KEBKG:GWD         -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    KETRB:TURBULENCE  -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    KESRF:TURBULENCE  -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    KEINT:TURBULENCE  -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    KETOP:TURBULENCE  -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    KEMST:MOIST       -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   CONVKE:DYN         -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  CONVPHI:DYN         -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  CONVCPT:DYN         -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEDYN:DYN TEDYN:DYN CONVKE:DYN CONVPHI:DYN -NAME KEGEN1 -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT PEDYN:DYN CONVCPT:DYN                      -NAME KEGEN2 -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEDYN:DYN TEDYN:DYN CONVKE:DYN CONVPHI:DYN PEDYN:DYN CONVCPT:DYN -NAME KEGENNET -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT KEDYN:DYN TEDYN:DYN CONVKE:DYN CONVPHI:DYN KEGEN:DYN -NAME KEGEND1 -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT PEDYN:DYN CONVCPT:DYN KEGEN:DYN -NAME KEGEND2 -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1



# Turbulence
# ----------
    set levels = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300'

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT      KM:TURBULENCE  -LEVELS $levels -PTOP 300 -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT      KH:TURBULENCE  -LEVELS $levels -PTOP 300 -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT    KMLS:TURBULENCE  -LEVELS $levels -PTOP 300 -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT    KHLS:TURBULENCE  -LEVELS $levels -PTOP 300 -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   KHSFC:TURBULENCE  -LEVELS $levels -PTOP 300 -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   KHRAD:TURBULENCE  -LEVELS $levels -PTOP 300 -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT     EKH:TURBULENCE  -LEVELS $levels -PTOP 300 -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT     EKM:TURBULENCE  -LEVELS $levels -PTOP 300 -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT      RI:TURBULENCE  -LEVELS $levels           -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT  INTDIS:TURBULENCE  -LEVELS $levels -PTOP 300 -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT  TOPDIS:TURBULENCE  -LEVELS $levels -PTOP 300 -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Moist Processes
# ---------------
    set levels = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300 250 200 150 100'
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT    OMEGA:DYN    -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT     QLLS:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT     QLCN:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT     QILS:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT     QICN:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT QGRAUPEL:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT    QRAIN:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT    QSNOW:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT     CLLS:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT     CLCN:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT     FCLD:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT    QLTOT:AGCM   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT    QITOT:AGCM   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT  CNV_MF0:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT  CNV_MFD:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT  CNV_MFC:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   RSU_LS:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT       RL:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT       RI:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT    TAUIR:IRRAD  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   TAUCLI:SOLAR  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   TAUCLW:SOLAR  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   REV_CN:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   REV_AN:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   REV_LS:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   RSU_AN:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   RSU_CN:MOIST  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT    MUPDP:MOIST  -ALIAS MUPDP   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT    MDNDP:MOIST  -ALIAS MDNDP   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT    MUPMD:MOIST  -ALIAS MUPMD   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT    MUPSH:MOIST  -ALIAS MUPSH   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   MFD_SC:MOIST  -ALIAS MFDSC   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   UMF_SC:MOIST  -ALIAS UMFSC   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT   DCM_SC:MOIST  -ALIAS DCMSC   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT  ENTR_DP:MOIST  -ALIAS ENTRDP  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT  ENTR_MD:MOIST  -ALIAS ENTRMD  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT  ENTR_SH:MOIST  -ALIAS ENTRSH  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT  ENTR_SC:MOIST  -ALIAS ENTRSC  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT CNV_TOPP_DP:MOIST  -ALIAS CNVTOPPDP  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT CNV_TOPP_MD:MOIST  -ALIAS CNVTOPPMD  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT CNV_TOPP_SH:MOIST  -ALIAS CNVTOPPSH  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT CLDTOP_SC:MOIST    -ALIAS CLDTOPSC   -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT CNV_FRC:MOIST      -ALIAS CNV_FRC    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT PLCL_SC:MOIST      -ALIAS PLCLSC     -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT PLFC_SC:MOIST      -ALIAS PLFCSC     -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT PINV_SC:MOIST      -ALIAS PINVSC     -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT PREL_SC:MOIST      -ALIAS PRELSC     -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT PBUP_SC:MOIST      -ALIAS PBUPSC     -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT MFDP:MOIST         -ALIAS MFDP       -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT MFMD:MOIST         -ALIAS MFMD       -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT MFSH:MOIST         -ALIAS MFSH       -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT CBMF_SC:MOIST      -ALIAS CBMF_SC    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT TAU_BL:MOIST       -ALIAS TAU_BL     -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT TAU_DP:MOIST       -ALIAS TAU_DP     -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid  -EXPORT TAU_MD:MOIST       -ALIAS TAU_MD     -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Surface/2-D
# -----------
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT TROPP_BLENDED:AGCM   -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT         TROPT:AGCM   -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT         TROPQ:AGCM   -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT     ZPBL:TURBULENCE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT TQL:AGCM                      -ALIAS lwp  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT TQV:AGCM                      -ALIAS tpw  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT TQL:AGCM TQR:AGCM  -NAME tlwp -ALIAS tlwp -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT TQI:AGCM                      -ALIAS tqi  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT TQR:AGCM                      -ALIAS tqr  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT TQS:AGCM                      -ALIAS tqs  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT TQG:AGCM                      -ALIAS tqg  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT RAS_TIME:MOIST    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT   CLDTMP:SOLAR    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT   CLDPRS:SOLAR    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT    CLDLO:SOLAR    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT    CLDMD:SOLAR    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT    CLDHI:SOLAR    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT    CLDTT:SOLAR    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT    TAULO:SOLAR    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT    TAUMD:SOLAR    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT    TAUHI:SOLAR    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT    TAUTT:SOLAR    -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT      SLP:DYN      -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT       US:DYN      -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT       VS:DYN      -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT    SPEED:DYN      -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT       TS:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT       QS:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT     THAT:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT     QHAT:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT     EMIS:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT       CT:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT       CQ:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT       CN:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT       CM:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT       Z0:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT      Z0H:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT      LAI:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT      GRN:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT   SNOMAS:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT   TSLAND:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT      T2M:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT      Q2M:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT     WET1:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT     GUST:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT     VENT:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT       RI:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT      DMDTDYN:DYN  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT     DMDT:PHYSICS  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT    UU10M:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT     U10M:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT     V10M:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT    USTAR:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template  -EXPID $expid  -EXPORT   USTARW:SURFACE  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DMDTDYN:DYN  DMDTANA:DYN              -NAME DMDTDYNANA     -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DMDTDYN:DYN  DMDTANA:DYN DMDT:PHYSICS -NAME DMDTDYNANAPHY  -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Gravity-Wave Drag
# -----------------
    if( $plot == $plotname.$n ) $grads $batch -l -c "run  $GEOSUTIL/plots/gwd/gwd $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    set levels = '400 300 200 100 50 10 5 2 1 .4 .2 .1 .04 .02'
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  TTMGW:GWD    -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   DUDT:GWD    -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   DVDT:GWD    -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  DUDT_BKG:GWD -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  DVDT_BKG:GWD -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  DTDT_BKG:GWD -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  DUDT_ORO:GWD -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  DVDT_ORO:GWD -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  DTDT_ORO:GWD -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Radiation
# ---------
    if( $plot == $plotname.$n ) $grads $batch -l -c "run  $GEOSUTIL/plots/rad/rad $expid $output $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  OLA:IRRAD    OLC:IRRAD  -NAME OLRCAF    -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  LCS:IRRAD    LAS:IRRAD  -NAME LWGNETCAF -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  RSR:SOLAR  RSRNA:SOLAR  -NAME SWTNETAF  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  RSC:SOLAR  RSCNA:SOLAR  -NAME SWTNETCAF -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT RSRS:SOLAR RSRSNA:SOLAR  -NAME SWGNETAF  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT RSCS:SOLAR RSCSNA:SOLAR  -NAME SWGNETCAF -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT ALBEDO:SOLAR -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT ALBVR:SOLAR  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT ALBVF:SOLAR  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT ALBNR:SOLAR  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT ALBNF:SOLAR  -SEASON $seasons  -OUTPUT $output  -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Tendencies
# ----------
    set levels = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300 250 200 150 100 70 50 30 20 10 7 5 3 1 0.4'
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   DUDTDYN:DYN     -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   DVDTDYN:DYN     -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   DTDTDYN:DYN     -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  DQVDTDYN:DYN     -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      DUDT:MOIST   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      DVDT:MOIST   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      DQDT:MOIST   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     DQLDT:MOIST   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     DQIDT:MOIST   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     DQADT:MOIST   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  DTDTFRIC:MOIST   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    UIT:PHYSICS    -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    VIT:PHYSICS    -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    TIM:PHYSICS    -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   QVIT:PHYSICS    -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    TIT:PHYSICS    -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    TIF:PHYSICS    -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  RADLW:RADIATION  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  RADSW:RADIATION  -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     DMDTANA:DYN                   -SEASON $seasons -OUTPUT $output           -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   DPSDT_CON:AGCM                  -SEASON $seasons -OUTPUT $output           -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQVDTANAINT:DYN                   -SEASON $seasons -OUTPUT $output           -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT       DUDT:AGCM   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT       DVDT:AGCM   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT       DTDT:AGCM   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      DQVDT:AGCM   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   DUDT_ANA:AGCM   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   DVDT_ANA:AGCM   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   DTDT_ANA:AGCM   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  DQVDT_ANA:AGCM   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  DQVDT_CON:AGCM   -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  DTDT_micro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQVDT_micro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQLDT_micro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQIDT_micro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQADT_micro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQRDT_micro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQSDT_micro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQGDT_micro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  DTDT_macro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQVDT_macro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQLDT_macro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQIDT_macro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQADT_macro:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     DTDT_DC:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    DQVDT_DC:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    DQLDT_DC:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    DQIDT_DC:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    DQADT_DC:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     DTDT_SC:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    DQVDT_SC:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    DQLDT_SC:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    DQIDT_SC:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    DQADT_SC:MOIST -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUDT:MOIST    UIT:PHYSICS   DUDT:GWD                                    -NAME DUDTPHY -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DVDT:MOIST    VIT:PHYSICS   DVDT:GWD                                    -NAME DVDTPHY -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQDT:MOIST   QVIT:PHYSICS                                               -NAME DQDTPHY -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  TIM:PHYSICS  TIT:PHYSICS  TTMGW:GWD  RADLW:RADIATION  RADSW:RADIATION  -NAME DTDTPHY -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT                                       RADLW:RADIATION  RADSW:RADIATION  -NAME DTDTRAD -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUDT:MOIST    UIT:PHYSICS   DUDT:GWD                                     DUDTDYN:DYN  -NAME DUDTTOT -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DVDT:MOIST    VIT:PHYSICS   DVDT:GWD                                     DVDTDYN:DYN  -NAME DVDTTOT -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DQDT:MOIST   QVIT:PHYSICS                                               DQVDTDYN:DYN  -NAME DQDTTOT -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  TIM:PHYSICS  TIT:PHYSICS  TTMGW:GWD  RADLW:RADIATION  RADSW:RADIATION   DTDTDYN:DYN  -NAME DTDTTOT -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG OFF -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Chemistry
# ---------
    set levels = '1000 850 500 250 100 85 70 50 30 10 5 3 1 .4 .2 .1 .04 .02'
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   GMIAOA:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   GMIH2O:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT       O3:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     N2O5:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     HNO4:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   CLONO2:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      HCL:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     HOCL:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     H2O2:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      N2O:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      CL2:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     OCLO:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     BRCL:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      HBR:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   BRONO2:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      CH4:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     HOBR:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT       CO:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT HNO3COND:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     HNO3:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  H2OCOND:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    CFCL3:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   CF2CL2:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT   CFC113:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT HCFC141B:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT HCFC142B:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     CCL4:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT  CH3CCL3:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    CH3CL:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    CH3BR:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    H2402:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT        O:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      O1D:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT        N:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT       NO:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      NO2:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      NO3:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT        H:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT       OH:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      MO2:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT       MP:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      HO2:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT       CL:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      CLO:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      BRO:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT       BR:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT    CL2O2:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     CH2O:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -ZLOG ON -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    set levels = '1000 900 850 700 500 250 100 85'
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT      PAN:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     ISOP:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     ALD2:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     ALK4:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     C2H6:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     C3H8:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     PRPE:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT     ACET:GMICHEM -LEVELS $levels -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# GOCART dust and aerosols
# ------------------------
    set INFO  = "-MATH LOG -SEASON $seasons -OUTPUT $output -DEBUG $debug "
# ---tavg2d_aer_x---
# Total:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT TOTEXTTAU:GOCART2G                    -ALIAS TOTEXTTAU   $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT TOTSCATAU:GOCART2G                    -ALIAS TOTSCATAU   $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT TOTANGSTR:GOCART2G                    -ALIAS TOTANGSTR   $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT TOTSTEXTTAU:GOCART2G                  -ALIAS TOTSTEXTTAU $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT TOTSTSCATAU:GOCART2G                  -ALIAS TOTSTSCATAU $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT PM25:GOCART2G                         -ALIAS PM25        $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT PM:GOCART2G                           -ALIAS PM          $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Dust:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUEM:DU:001                           -ALIAS DUEM001     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUEM:DU:002                           -ALIAS DUEM002     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUEM:DU:003                           -ALIAS DUEM003     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUEM:DU:004                           -ALIAS DUEM004     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUEM:DU:005                           -ALIAS DUEM005     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUSD:DU:001                           -ALIAS DUSD001     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUSD:DU:002                           -ALIAS DUSD002     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUSD:DU:003                           -ALIAS DUSD003     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUSD:DU:004                           -ALIAS DUSD004     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUSD:DU:005                           -ALIAS DUSD005     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUDP:DU:001                           -ALIAS DUDP001     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUDP:DU:002                           -ALIAS DUDP002     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUDP:DU:003                           -ALIAS DUDP003     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUDP:DU:004                           -ALIAS DUDP004     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUDP:DU:005                           -ALIAS DUDP005     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUWT:DU:001                           -ALIAS DUWT001     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUWT:DU:002                           -ALIAS DUWT002     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUWT:DU:003                           -ALIAS DUWT003     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUWT:DU:004                           -ALIAS DUWT004     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUWT:DU:005                           -ALIAS DUWT005     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUSMASS:DU                            -ALIAS DUSMASS     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUCMASS:DU                            -ALIAS DUCMASS     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUSMASS25:DU                          -ALIAS DUSMASS25   $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUCMASS25:DU                          -ALIAS DUCMASS25   $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUEXTT25:DU                           -ALIAS DUEXTT25    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUSCAT25:DU                           -ALIAS DUSCAT25    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUEXTTAU:DU                           -ALIAS DUEXTTAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUSCATAU:DU                           -ALIAS DUSCATAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUSTEXTTAU:DU                         -ALIAS DUSTEXTTAU  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUSTSCATAU:DU                         -ALIAS DUSTSCATAU  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUANGSTR:DU                           -ALIAS DUANGSTR    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUEXTTFM:DU                           -ALIAS DUEXTTFM    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUSCATFM:DU                           -ALIAS DUSCATFM    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUFLUXU:DU                            -ALIAS DUFLUXU     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUFLUXV:DU                            -ALIAS DUFLUXV     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT MCHEMTRI%DU::DUIM:PHYSICS             -ALIAS DUSV        $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Salt:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSEM:SS:001                           -ALIAS SSEM001     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSEM:SS:002                           -ALIAS SSEM002     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSEM:SS:003                           -ALIAS SSEM003     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSEM:SS:004                           -ALIAS SSEM004     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSEM:SS:005                           -ALIAS SSEM005     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSSD:SS:001                           -ALIAS SSSD001     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSSD:SS:002                           -ALIAS SSSD002     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSSD:SS:003                           -ALIAS SSSD003     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSSD:SS:004                           -ALIAS SSSD004     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSSD:SS:005                           -ALIAS SSSD005     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSDP:SS:001                           -ALIAS SSDP001     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSDP:SS:002                           -ALIAS SSDP002     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSDP:SS:003                           -ALIAS SSDP003     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSDP:SS:004                           -ALIAS SSDP004     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSDP:SS:005                           -ALIAS SSDP005     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSWT:SS:001                           -ALIAS SSWT001     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSWT:SS:002                           -ALIAS SSWT002     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSWT:SS:003                           -ALIAS SSWT003     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSWT:SS:004                           -ALIAS SSWT004     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSWT:SS:005                           -ALIAS SSWT005     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSSMASS:SS                            -ALIAS SSSMASS     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSCMASS:SS                            -ALIAS SSCMASS     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSSMASS25:SS                          -ALIAS SSSMASS25   $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSCMASS25:SS                          -ALIAS SSCMASS25   $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSEXTT25:SS                           -ALIAS SSEXTT25    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSSCAT25:SS                           -ALIAS SSSCAT25    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSEXTTAU:SS                           -ALIAS SSEXTTAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSSCATAU:SS                           -ALIAS SSSCATAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSSTEXTTAU:SS                         -ALIAS SSSTEXTTAU  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSSTSCATAU:SS                         -ALIAS SSSTSCATAU  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSANGSTR:SS                           -ALIAS SSANGSTR    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSEXTTFM:SS                           -ALIAS SSEXTTFM    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSSCATFM:SS                           -ALIAS SSSCATFM    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSFLUXU:SS                            -ALIAS SSFLUXU     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSFLUXV:SS                            -ALIAS SSFLUXV     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT MCHEMTRI%SS::SSIM:PHYSICS             -ALIAS SSSV        $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Sulfates:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUEM:SU:DMSEM                         -ALIAS DMSEM       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUEM:SU:SO2EM                         -ALIAS SO2EM       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUEM:SU:SO4EM                         -ALIAS SO4EM       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUEM:SU:MSAEM                         -ALIAS MSAEM       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUDP:SU:DMSDP                         -ALIAS DMSDP       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUDP:SU:SO2DP                         -ALIAS SO2DP       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUDP:SU:SO4DP                         -ALIAS SO4DP       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUDP:SU:MSADP                         -ALIAS MSADP       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUWT:SU:DMSWT                         -ALIAS DMSWT       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUWT:SU:SO2WT                         -ALIAS SO2WT       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUWT:SU:SO4WT                         -ALIAS SO4WT       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUWT:SU:MSAWT                         -ALIAS MSAWT       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUSD:SU:DMSSD                         -ALIAS DMSSD       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUSD:SU:SO2SD                         -ALIAS SO2SD       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUSD:SU:SO4SD                         -ALIAS SO4SD       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUSD:SU:MSASD                         -ALIAS MSASD       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO2SMASS:SU                           -ALIAS SO2SMASS    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO2CMASS:SU                           -ALIAS SO2CMASS    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO4SMASS:SU                           -ALIAS SO4SMASS    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO4CMASS:SU                           -ALIAS SO4CMASS    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DMSSMASS:SU                           -ALIAS DMSSMASS    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DMSCMASS:SU                           -ALIAS DMSCMASS    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUPSO2:SU                             -ALIAS SUPSO2      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUPSO4G:SU                            -ALIAS SUPSO4G     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUPSO4AQ:SU                           -ALIAS SUPSO4AQ    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUPSO4WT:SU                           -ALIAS SUPSO4WT    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUPMSA:SU                             -ALIAS SUPMSA      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUEXTTAU:SU                           -ALIAS SUEXTTAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUSCATAU:SU                           -ALIAS SUSCATAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUSTEXTTAU:SU                         -ALIAS SUSTEXTTAU  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUSTSCATAU:SU                         -ALIAS SUSTSCATAU  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUANGSTR:SU                           -ALIAS SUANGSTR    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO4EMAN:SU                            -ALIAS SO4EMAN     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO2EMAN:SU                            -ALIAS SO2EMAN     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO2EMBB:SU                            -ALIAS SO2EMBB     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO2EMVN:SU                            -ALIAS SO2EMVN     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO2EMVE:SU                            -ALIAS SO2EMVE     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUFLUXU:SU                            -ALIAS SUFLUXU     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SUFLUXV:SU                            -ALIAS SUFLUXV     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT MCHEMTRI%SU::SO4IM:PHYSICS            -ALIAS SUSV        $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Nitrates:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT HNO3SMASS:NI                          -ALIAS HNO3SMASS   $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH3SMASS:NI                           -ALIAS NH3SMASS    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH4SMASS:NI                           -ALIAS NH4SMASS    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NISMASS:NI                            -ALIAS NISMASS     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NISMASS25:NI                          -ALIAS NISMASS25   $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT HNO3CMASS:NI                          -ALIAS HNO3CMASS   $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH3CMASS:NI                           -ALIAS NH3CMASS    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH4CMASS:NI                           -ALIAS NH4CMASS    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NICMASS:NI                            -ALIAS NICMASS     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NICMASS25:NI                          -ALIAS NICMASS25   $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NIEXTTFM:NI                           -ALIAS NIEXTTFM    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NISCATFM:NI                           -ALIAS NISCATFM    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NIEXTTAU:NI                           -ALIAS NIEXTTAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NISCATAU:NI                           -ALIAS NISCATAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NIANGSTR:NI                           -ALIAS NIANGSTR    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NIPNO3AQ:NI                           -ALIAS NIPNO3AQ    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NIPNH4AQ:NI                           -ALIAS NIPNH4AQ    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NIPNH3AQ:NI                           -ALIAS NIPNH3AQ    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NIHT:NI                               -ALIAS NIHT        $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NISD:NI                               -ALIAS NISD        $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NIDP:NI                               -ALIAS NIDP        $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NIWT:NI                               -ALIAS NIWT        $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH3EM:NI                              -ALIAS NH3EM       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH3DP:NI                              -ALIAS NH3DP       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH3WT:NI                              -ALIAS NH3WT       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH4SD:NI                              -ALIAS NH4SD       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH4DP:NI                              -ALIAS NH4DP       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH4WT:NI                              -ALIAS NH4WT       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NIFLUXU:NI                            -ALIAS NIFLUXU     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NIFLUXV:NI                            -ALIAS NIFLUXV     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT MCHEMTRI%NI::NO3an1IM:PHYSICS         -ALIAS NISV        $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT MCHEMTRI%NI::NH3IM:PHYSICS            -ALIAS NH3SV       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT MCHEMTRI%NI::NH4aIM:PHYSICS           -ALIAS NH4SV       $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Black Carbon:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcEM:CA.bc:BCPHOBICEM              -ALIAS BCPHOBICEM  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcEM:CA.bc:BCPHILICEM              -ALIAS BCPHILICEM  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcDP:CA.bc:BCPHOBICDP              -ALIAS BCPHOBICDP  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcDP:CA.bc:BCPHILICDP              -ALIAS BCPHILICDP  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcWT:CA.bc:BCPHOBICWT              -ALIAS BCPHOBICWT  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcWT:CA.bc:BCPHILICWT              -ALIAS BCPHILICWT  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcSD:CA.bc:BCPHOBICSD              -ALIAS BCPHOBICSD  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcSD:CA.bc:BCPHILICSD              -ALIAS BCPHILICSD  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcSMASS:CA.bc                      -ALIAS BCSMASS     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcCMASS:CA.bc                      -ALIAS BCCMASS     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcEXTTAU:CA.bc                     -ALIAS BCEXTTAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcSCATAU:CA.bc                     -ALIAS BCSCATAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcSTEXTTAU:CA.bc                   -ALIAS BCSTEXTTAU  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcSTSCATAU:CA.bc                   -ALIAS BCSTSCATAU  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcANGSTR:CA.bc                     -ALIAS BCANGSTR    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcHYPHIL:CA.bc                     -ALIAS BCPHOB2PHIL $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcEMBB:CA.bc                       -ALIAS BCEMBB      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcEMBF:CA.bc                       -ALIAS BCEMBF      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcEMAN:CA.bc                       -ALIAS BCEMAN      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcFLUXU:CA.bc                      -ALIAS BCFLUXU     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcFLUXV:CA.bc                      -ALIAS BCFLUXV     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT MCHEMTRI%CA.bc::CA.bcphilicIM:PHYSICS -ALIAS BCSV        $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Organic Carbon:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocEM:CA.oc:OCPHOBICEM              -ALIAS OCPHOBICEM  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocEM:CA.oc:OCPHILICEM              -ALIAS OCPHILICEM  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocDP:CA.oc:OCPHOBICDP              -ALIAS OCPHOBICDP  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocDP:CA.oc:OCPHILICDP              -ALIAS OCPHILICDP  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocWT:CA.oc:OCPHOBICWT              -ALIAS OCPHOBICWT  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocWT:CA.oc:OCPHILICWT              -ALIAS OCPHILICWT  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocSD:CA.oc:OCPHOBICSD              -ALIAS OCPHOBICSD  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocSD:CA.oc:OCPHILICSD              -ALIAS OCPHILICSD  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocSMASS:CA.oc                      -ALIAS OCSMASS     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocCMASS:CA.oc                      -ALIAS OCCMASS     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocEXTTAU:CA.oc                     -ALIAS OCEXTTAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocSCATAU:CA.oc                     -ALIAS OCSCATAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocSTEXTTAU:CA.oc                   -ALIAS OCSTEXTTAU  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocSTSCATAU:CA.oc                   -ALIAS OCSTSCATAU  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocANGSTR:CA.oc                     -ALIAS OCANGSTR    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocHYPHIL:CA.oc                     -ALIAS OCPHOB2PHIL $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocEMBB:CA.oc                       -ALIAS OCEMBB      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocEMBF:CA.oc                       -ALIAS OCEMBF      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocEMAN:CA.oc                       -ALIAS OCEMAN      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocEMBG:CA.oc                       -ALIAS OCEMBG      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocPSOA:CA.oc                       -ALIAS OCPSOA      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocFLUXU:CA.oc                      -ALIAS OCFLUXU     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocFLUXV:CA.oc                      -ALIAS OCFLUXV     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT MCHEMTRI%CA.oc::CA.ocphilicIM:PHYSICS -ALIAS OCSV        $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Brown Carbon:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brEM:CA.br:BRPHOBICEM              -ALIAS BRPHOBICEM  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brEM:CA.br:BRPHILICEM              -ALIAS BRPHILICEM  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brDP:CA.br:BRPHOBICDP              -ALIAS BRPHOBICDP  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brDP:CA.br:BRPHILICDP              -ALIAS BRPHILICDP  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brWT:CA.br:BRPHOBICWT              -ALIAS BRPHOBICWT  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brWT:CA.br:BRPHILICWT              -ALIAS BRPHILICWT  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brSD:CA.br:BRPHOBICSD              -ALIAS BRPHOBICSD  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brSD:CA.br:BRPHILICSD              -ALIAS BRPHILICSD  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brSMASS:CA.br                      -ALIAS BRSMASS     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brCMASS:CA.br                      -ALIAS BRCMASS     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brEXTTAU:CA.br                     -ALIAS BREXTTAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brSCATAU:CA.br                     -ALIAS BRSCATAU    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brSTEXTTAU:CA.br                   -ALIAS BRSTEXTTAU  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brSTSCATAU:CA.br                   -ALIAS BRSTSCATAU  $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brANGSTR:CA.br                     -ALIAS BRANGSTR    $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brHYPHIL:CA.br                     -ALIAS BRPHOB2PHIL $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brEMBB:CA.br                       -ALIAS BREMBB      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brEMBF:CA.br                       -ALIAS BREMBF      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brEMAN:CA.br                       -ALIAS BREMAN      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brPSOA:CA.br                       -ALIAS BRPSOA      $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brFLUXU:CA.br                      -ALIAS BRFLUXU     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brFLUXV:CA.br                      -ALIAS BRFLUXV     $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT MCHEMTRI%CA.br::CA.brphilicIM:PHYSICS -ALIAS BRSV        $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# ---tavg3d_aer_p---
# Dust:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DUMASS:DU       -ALIAS DU  -LEVELS misc -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Salt:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SSMASS:SS       -ALIAS SS  -LEVELS misc -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Sulfates:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO2:SU          -ALIAS SO2 -LEVELS misc -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO4:SU          -ALIAS SO4 -LEVELS misc -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Nitrates:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH3MASS:NI      -ALIAS NH3 -LEVELS misc -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH4MASS:NI      -ALIAS NH4 -LEVELS misc -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NIMASS:NI       -ALIAS NI  -LEVELS misc -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Black Carbon
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcMASS:CA.bc -ALIAS BC  -LEVELS misc -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Organic Carbon:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocMASS:CA.oc -ALIAS OC  -LEVELS misc -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Brown Carbon:
    if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brMASS:CA.br -ALIAS BR  -LEVELS misc -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# ---inst3d_aer_v---
    set levels = '1000 975 950 925 900 850 800 750 700 650 600 550 500 400 300 250 200 150 100 85 70'
# Dust:
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DU001:DU          -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DU002:DU          -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DU003:DU          -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DU004:DU          -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DU005:DU          -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Salt: 
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SS001:SS          -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SS002:SS          -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SS003:SS          -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SS004:SS          -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SS005:SS          -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Sulfates:
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT DMS:SU            -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO2:SU            -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT SO4:SU            -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT MSA:SU            -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Nitrates:
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH3:NI            -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NH4a:NI           -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NO3an1:NI         -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NO3an2:NI         -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT NO3an3:NI         -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Black Carbon:
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcphilic:CA.bc -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.bcphobic:CA.bc -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Organic Carbon:
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocphilic:CA.oc -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.ocphobic:CA.oc -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Brown Carbon:
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brphilic:CA.br -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    # if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT CA.brphobic:CA.br -LEVELS $levels -ZLOG MULTI $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Miscellaneous Plots
# -------------------
    if( -e $homdir/HISTORY.rc ) then
    set EXPORTS = `$GEOSUTIL/plots/get_exports  $homdir/HISTORY.rc  landscape.script`
    foreach export ($EXPORTS)
      if( $plot == $plotname.$n ) $grads $batch -l -c "run template -EXPID $expid -EXPORT $export -LEVELS misc -SEASON $seasons -OUTPUT ${output}/misc -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
    end
    endif

# User-Interactive Plots
# ----------------------
set EXPORT = `echo $plot | cut -d: -f1`
set GC     = `echo $plot | cut -d: -f2`
set level  = `echo $plot | cut -d: -f3`
if( $EXPORT != $GC ) then
       if( $level == '' | $level == 'Z' | $level == 'z' ) set level = misc
       $grads $batch -l -c "run template -EXPID $expid -EXPORT ${EXPORT}:${GC} -LEVELS $level -SEASON $seasons -OUTPUT ${output}/misc -DEBUG $debug -ZLOG $zlog "
endif

#######################################################################################

if( $LIST == TRUE ) echo $plots

exit
