#!/bin/csh -f

#######################################################################################
# This script is the driver for QUICKPLOT plots in PORTRAIT mode.
# To produce a list of PORTRAIT plots, simply issue the following 3 commands:
#    (1)  portrait.script -v -list -source $SOURCE > & dummy
#    (2)  grep "plot ==" dummy | tee portrait.list
#    (3)  /bin/rm dummy
# where $SOURCE is an OPTIONAL valid SOURCE directory containing a HISTORY.rc
#######################################################################################


set plots = "residual"
set MAKE_LIST = FALSE

setenv ORIENTATION PORTRAIT
if ( ! $?LONSENV ) then
  setenv LONSENV "0 360"
endif
if ( ! $?LATSENV ) then
  setenv LATSENV "-90 90"
endif

# Set Defaults
# ------------
set    batch = " "
set    debug = "no_debug"
set    expid = '$EXPID'
set   source = '$SOURCE'
set     plot = 'plot'
set   output = '$OUTPUT'
set geosutil = '$GEOSUTIL'
set  seasons = '$SEASON'
set    grads = "grads"


if(! $?STD_DEV ) then
                                setenv STD_DEV FALSE
                                setenv DO_STD  FALSE
else if( ${STD_DEV} == 'true' ) setenv DO_STD  TRUE
endif

if(! $?TAYLOR ) then
   set TAYLOR = FALSE
else
   set TAYLOR = `echo $TAYLOR | tr "[:lower:]" "[:upper:]"`
endif

if(! $?CMPEXP      ) setenv CMPEXP      NULL
if(! $?CMPEXP_ONLY ) setenv CMPEXP_ONLY NULL

@ nmax = $#argv

# Parse command line
# ------------------
@       n  = 1
while( $n <= $nmax )

       if( "$argv[$n]" == "-list" ) then
               set MAKE_LIST = TRUE
       endif

       if( "$argv[$n]" == "-v" ) then
               set echo
       endif

       if( "$argv[$n]" == "-expid" ) then
                    @ n = $n + 1
             set expid  = $argv[$n]
       endif
       if( "$argv[$n]" == "-source" ) then
                    @ n = $n + 1
           set source   = $argv[$n]
       endif
       if( "$argv[$n]" == "-plot"   ) then
                    @ n = $n + 1
             set plot   = $argv[$n]
       endif
       if( "$argv[$n]" == "-output" ) then
                    @ n = $n + 1
             set output = $argv[$n]
       endif
       if( "$argv[$n]" == "-geosutil" ) then
                    @ n = $n + 1
             set geosutil = $argv[$n]
       endif
       if( "$argv[$n]" == "-debug"   ) then
             set debug = "debug"
       endif
       if( "$argv[$n]" == "-zlog"   ) then
                    @ n = $n + 1
             set zlog  = $argv[$n]
       endif
       if( "$argv[$n]" == "-grads"   ) then
                    @ n = $n + 1
             set grads = $argv[$n]
       endif
       if( "$argv[$n]" == "-batch"   ) then
             set batch = "-b"
       endif
       if( "$argv[$n]" == "-season"  ) then
                    @ n = $n + 1
                                      set seasons = ""
                                      set next   = $argv[$n]
                                      set bit    = `echo $next | cut -c1-1`
                                      while( "$bit" != "-" )
                                         set seasons = `echo $seasons $next`
                                          @   n  = $n + 1
                                         if( $n <= $nmax ) then
                                             set next = $argv[$n]
                                             set bit  = `echo $next | cut -c1-1`
                                         else
                                             set bit  = "-"
                                         endif
                                      end
                                             @ n = $n - 1
       endif
     @ n = $n + 1
end

if( $MAKE_LIST == FALSE ) then
    echo "Portrait Script"
    echo "---------------"
    echo "   expid: $expid"
    echo "  source: $source"
    echo "    plot: $plot"
    echo "  output: $output"
    echo "geosutil: $geosutil"
    echo "   debug: $debug"
    echo "  season: $seasons"
    echo "  TAYLOR: $TAYLOR"
    echo " STD_DEV: $STD_DEV"
endif

if( -e $source/.HOMDIR ) then
    set homdir = `cat $source/.HOMDIR`
else
    set homdir = $source
endif

set  plot_type = `echo $plot | cut -c2-5`
if( $plot_type == 'quad' ) then
    setenv PLOT_QUAD true
else
    setenv PLOT_QUAD false
endif

#######################################################################################
#                               Create LIST of Plots
#######################################################################################

     set plotname = ${ORIENTATION}
     @ n = 1

#######################################################################################

# Taylor Plots
# ------------
if( $MAKE_LIST == TRUE | ( $TAYLOR == "TRUE" & $CMPEXP_ONLY == "FALSE" ) ) then
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_olr                $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_cloud              $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_lwp                $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_tpw                $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_tskin              $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_uflux              $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_eflux              $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_hflux              $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog U   DYN   850 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog V   DYN   850 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog T   DYN   850 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog Q   MOIST 850 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog U   DYN   500 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog V   DYN   500 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog T   DYN   500 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog Q   MOIST 500 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog U   DYN   200 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog V   DYN   200 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog T   DYN   200 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog Q   MOIST 200 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog ZLE DYN   300 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog ZLE DYN   500 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog SLP DYN  1000 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
endif


# Prognostic Zonal Mean Comparisons
# ---------------------------------
     set EXPORTS = `echo U   V   T   Q     RH2   ZLE OMEGA O3         QLTOT QITOT`
     set GCS     = `echo DYN DYN DYN MOIST MOIST DYN DYN   CHEMISTRY  AGCM  AGCM `
     @ k = 0
     foreach EXPORT ($EXPORTS)
       @ k = $k + 1
       set GC = $GCS[$k]
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/zcmp/progz $EXPORT $GC $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end


# Prognostic Horizontal Mean Dynamics Comparisons
# -----------------------------------------------
     if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/hcmp/hcmp2 SLP DYN 1000 $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     set EXPORTS = `echo U V T ZLE HE OMEGA CHI PSI`
     set LEVS = '1000 925 850 700 600 500 400 300 250 200 150 100 70 50 30 20 10 7 5 3 1 0.4'
     foreach EXPORT ($EXPORTS)
     foreach LEV    ($LEVS)
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/hcmp/hcmp2 $EXPORT DYN $LEV $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end

# Prognostic Horizontal Mean Moist Comparisons
# --------------------------------------------
     set EXPORTS = `echo Q RH2`
     set LEVS = '1000 925 850 700 600 500 400 300 250 200 150 100 70 50 30'
     foreach EXPORT ($EXPORTS)
     foreach LEV    ($LEVS)
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/hcmp/hcmp2 $EXPORT MOIST $LEV $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end

# Prognostic Horizontal Mean QL & QI Comparisons
# ----------------------------------------------
     set EXPORTS = `echo QLTOT QITOT`
     set LEVS = '1000 925 850 700 600 500 400 300 250 200 150 100 70 50 30'
     foreach EXPORT ($EXPORTS)
     foreach LEV    ($LEVS)
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/hcmp/hcmp2 $EXPORT AGCM $LEV $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end

# Prognostic Horizontal Mean Ozone Comparisons
# --------------------------------------------
     set EXPORTS = `echo O3`
     set LEVS    = '70 50 40 30 20 10 7 5 4 3 2 1 .7 .5 .4 .3 .2 .1'
     foreach EXPORT ($EXPORTS)
     foreach LEV    ($LEVS)
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/hcmp/hcmp2 $EXPORT CHEMISTRY $LEV $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end

# Prognostic Horizontal Dynamics Variance Comparisons
# ---------------------------------------------------
     set VARS = `echo U_U V_V T_T ZLE_ZLE OMEGA_OMEGA KE_KE`
     set LEVS = '850 500 200 20'
     foreach VAR ($VARS)
     foreach LEV ($LEVS)
       set EXPORT = `echo $VAR | cut -d_ -f1`
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/quad/hquad -EXPID $expid -EXPORT1 ${EXPORT}:DYN -EXPORT2 ${EXPORT}:DYN -LEV $LEV -SEASON $seasons  -OUTPUT $output -DEBUG $debug" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end

# Prognostic Horizontal Moist Variance Comparisons
# ------------------------------------------------
     set VARS = `echo Q_Q`
     set LEVS = '850 500 200 20'
     foreach VAR ($VARS)
     foreach LEV ($LEVS)
       set EXPORT = `echo $VAR | cut -d_ -f1`
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/quad/hquad -EXPID $expid -EXPORT1 ${EXPORT}:MOIST -EXPORT2 ${EXPORT}:MOIST -LEV $LEV -SEASON $seasons  -OUTPUT $output -DEBUG $debug" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end

# Prognostic Horizontal Moist CoVariance Comparisons
# --------------------------------------------------
     set VARS = `echo U_V V_T V_Q OMEGA_T OMEGA_Q`
     set LEVS = '850 500 200 20'
     foreach VAR ($VARS)
     foreach LEV ($LEVS)
       set EXPORT1 = `echo $VAR | cut -d_ -f1`
       set EXPORT2 = `echo $VAR | cut -d_ -f2`
       set GRDCMP1 = DYN
       set GRDCMP2 = DYN
       if($EXPORT2 == Q ) set GRDCMP2 = MOIST
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/quad/hquad -EXPID $expid -EXPORT1 ${EXPORT1}:${GRDCMP1} -EXPORT2 ${EXPORT2}:${GRDCMP2} -LEV $LEV -SEASON $seasons -OUTPUT $output -DEBUG $debug" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end


# Residual Circulation
# Note: Always run MAKERES before running the Residual PORTRAIT and LANDSCAPE plots
# ---------------------------------------------------------------------------------
if( $plot == residual ) then
     $GEOSUTIL/plots/res/makeres $source

     setenv ORIENTATION PORTRAIT
     $grads $batch -p -c "run $GEOSUTIL/plots/res/res  $expid $output $debug $seasons "

     setenv ORIENTATION LANDSCAPE
     $grads $batch -l -c "run $GEOSUTIL/plots/res/res  $expid $output $debug $seasons "
     $grads $batch -l -c "run $GEOSUTIL/plots/res/setup_wstar $source $expid $output B $seasons "
     $grads $batch -l -c "run $GEOSUTIL/plots/res/setup_wstar $source $expid $output A $seasons "
     $grads $batch -l -c "run $GEOSUTIL/plots/res/setup_epflx $source $expid $output $debug $seasons "
     $grads $batch -l -c "run $GEOSUTIL/plots/zcmp/zcmp $expid $output $seasons "
endif


# Surface/2-D
# -----------
    set EXPORTS = "CN_PRCP:MOIST LS_PRCP:MOIST AN_PRCP:MOIST"
    set     OBS = "TPREC:MOIST"
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT $EXPORTS -OBS $OBS -NAME precip  -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 86400                    -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT $EXPORTS -OBS $OBS -NAME precip  -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 86400 -PREFIX LAND -LAND -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CN_PRCP:MOIST AN_PRCP:MOIST -OBS CN_PRCP:MOIST -NAME precipcn  -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 86400 -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LS_PRCP:MOIST               -OBS LS_PRCP:MOIST -NAME precipls  -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 86400 -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run  $GEOSUTIL/plots/precip/precip $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run  $GEOSUTIL/plots/olr/olr       $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run  $GEOSUTIL/plots/olr/olrcc5    $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   SH:SURFACE    -NAME hflux   -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 1 -PREFIX LAND  -LAND  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   SH:SURFACE    -NAME hflux   -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 1               -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   LHFX:SURFACE  -NAME eflux   -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 1 -PREFIX LAND  -LAND  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   LHFX:SURFACE  -NAME eflux   -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 1               -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TQL:AGCM           -OBS LWP:MOIST  -NAME lwp  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TQV:AGCM                           -NAME tpw  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TQL:AGCM TQR:AGCM  -OBS TLWP:AGCM  -NAME tlwp -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TQI:AGCM                           -NAME tqi  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TQR:AGCM                           -NAME tqr  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TQS:AGCM                           -NAME tqs  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TQG:AGCM                           -NAME tqg  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT     TS:SURFACE  -NAME sst          -EXPID $expid -OUTPUT $output -DEBUG $debug        -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT     TS:SURFACE  -NAME tskin        -EXPID $expid -OUTPUT $output -DEBUG $debug        -LAND  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT  SPEED:DYN      -NAME SPEED_ocean  -EXPID $expid -OUTPUT $output -DEBUG $debug        -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT  SPEED:DYN      -NAME SPEED_land   -EXPID $expid -OUTPUT $output -DEBUG $debug        -LAND  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT     US:DYN      -NAME US_ocean     -EXPID $expid -OUTPUT $output -DEBUG $debug        -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT     US:DYN      -NAME US_land      -EXPID $expid -OUTPUT $output -DEBUG $debug        -LAND  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT     VS:DYN      -NAME VS_ocean     -EXPID $expid -OUTPUT $output -DEBUG $debug        -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT     VS:DYN      -NAME VS_land      -EXPID $expid -OUTPUT $output -DEBUG $debug        -LAND  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT  UU10M:SURFACE  -NAME UU10M_ocean  -EXPID $expid -OUTPUT $output -DEBUG $debug        -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT  UU10M:SURFACE  -NAME UU10M_land   -EXPID $expid -OUTPUT $output -DEBUG $debug        -LAND  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   U10M:SURFACE  -NAME U10M_ocean   -EXPID $expid -OUTPUT $output -DEBUG $debug        -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   U10M:SURFACE  -NAME U10M_land    -EXPID $expid -OUTPUT $output -DEBUG $debug        -LAND  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   V10M:SURFACE  -NAME V10M_ocean   -EXPID $expid -OUTPUT $output -DEBUG $debug        -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   V10M:SURFACE  -NAME V10M_land    -EXPID $expid -OUTPUT $output -DEBUG $debug        -LAND  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   TAUX:SURFACE  -NAME taux    -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 100 -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   TAUY:SURFACE  -NAME tauy    -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 100 -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT ALBEDO:SOLAR    -NAME albedo  -EXPID $expid -OUTPUT $output -DEBUG $debug                   -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT  ALBNF:SOLAR    -NAME albnf   -EXPID $expid -OUTPUT $output -DEBUG $debug                   -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT  ALBNR:SOLAR    -NAME albnr   -EXPID $expid -OUTPUT $output -DEBUG $debug                   -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT  ALBVF:SOLAR    -NAME albvf   -EXPID $expid -OUTPUT $output -DEBUG $debug                   -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT  ALBVR:SOLAR    -NAME albvr   -EXPID $expid -OUTPUT $output -DEBUG $debug                   -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TBISCCP:SATSIM                                                                       -NAME tb       -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT RADSRF:RADIATION LHFX:SURFACE SH:SURFACE -OBS QNET:RADIATION                         -NAME NETHEATG -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT EVAP:SURFACE CN_PRCP:MOIST LS_PRCP:MOIST AN_PRCP:MOIST -OBS EVAP:SURFACE TPREC:MOIST -NAME emp      -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Surface/2-D: Clouds
# -------------------
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDLO:SOLAR   -NAME cldlo   -EXPID $expid -OUTPUT $output -DEBUG $debug                  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDMD:SOLAR   -NAME cldmd   -EXPID $expid -OUTPUT $output -DEBUG $debug                  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDHI:SOLAR   -NAME cldhi   -EXPID $expid -OUTPUT $output -DEBUG $debug                  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDTT:SOLAR   -NAME cldtt   -EXPID $expid -OUTPUT $output -DEBUG $debug        -RC SRB   -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDTT:SOLAR   -NAME cldtt   -EXPID $expid -OUTPUT $output -DEBUG $debug        -RC ISCCP -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDTT:SOLAR   -NAME cldtt   -EXPID $expid -OUTPUT $output -DEBUG $debug -OCEAN -RC COADS -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CNV_TOPP_DP:MOIST  -NAME CNVTOPPDP  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CNV_TOPP_MD:MOIST  -NAME CNVTOPPMD  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CNV_TOPP_SH:MOIST  -NAME CNVTOPPSH  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDTOP_SC:MOIST    -NAME CLDTOPSC   -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CNV_FRC:MOIST      -NAME CNV_FRC    -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT PLCL_SC:MOIST      -NAME PLCLSC     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT PLFC_SC:MOIST      -NAME PLFCSC     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT PINV_SC:MOIST      -NAME PINVSC     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT PREL_SC:MOIST      -NAME PRELSC     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT PBUP_SC:MOIST      -NAME PBUPSC     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT MFDP:MOIST         -NAME MFDP       -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT MFMD:MOIST         -NAME MFMD       -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT MFSH:MOIST         -NAME MFSH       -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CBMF_SC:MOIST      -NAME CBMF_SC    -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TAU_BL:MOIST       -NAME TAU_BL     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TAU_DP:MOIST       -NAME TAU_DP     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TAU_MD:MOIST       -NAME TAU_MD     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Radiation: Shortwave
# --------------------
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME radswt      -EXPID $expid -EXPORT SLRTP:SOLAR                                                     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgnet      -EXPID $expid -EXPORT RSRS:SOLAR                                                      -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgnetc     -EXPID $expid -EXPORT RSCS:SOLAR -OBS SLRSFC:SOLAR ALBEDO:SOLAR                       -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgnetcf    -EXPID $expid -EXPORT RSCS:SOLAR RSRS:SOLAR -OBS SLRSFC:SOLAR ALBEDO:SOLAR RSRS:SOLAR -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgdwn   -EXPID $expid -EXPORT SLRSF:SOLAR              -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgdwnc  -EXPID $expid -EXPORT SLRSFC:SOLAR             -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgdwncf -EXPID $expid -EXPORT SLRSFC:SOLAR SLRSF:SOLAR -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME osr      -EXPID $expid -EXPORT RSR:SOLAR                -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME osrc     -EXPID $expid -EXPORT RSC:SOLAR                -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME osrcf    -EXPID $expid -EXPORT RSC:SOLAR RSR:SOLAR      -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgup     -EXPID $expid -EXPORT SLRSF:SOLAR  RSRS:SOLAR                                                                              -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgupc    -EXPID $expid -EXPORT SLRSFC:SOLAR RSCS:SOLAR -OBS ALBEDO:SOLAR SLRSFC:SOLAR                                               -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgupcf   -EXPID $expid -EXPORT SLRSFC:SOLAR RSCS:SOLAR SLRSF:SOLAR RSRS:SOLAR -OBS ALBEDO:SOLAR SLRSFC:SOLAR SLRSF:SOLAR RSRS:SOLAR -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
 

# Radiation: Longwave
# -------------------
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   OLC:IRRAD OLR:IRRAD OSRCLR:SOLAR OSR:SOLAR -NAME toacf     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT OLCC5:IRRAD OLR:IRRAD OSRCLR:SOLAR OSR:SOLAR -NAME toacf_cc5 -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   OLR:IRRAD  -NAME olr      -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   OLC:IRRAD  -NAME olrc     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT OLCC5:IRRAD  -NAME olrc_cc5 -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   OLC:IRRAD  OLR:IRRAD                       -NAME olrcf       -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT OLCC5:IRRAD  OLR:IRRAD                       -NAME olrcf_cc5   -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   LWS:IRRAD EMIS:SURFACE -OBS  SFCDWN:IRRAD  -NAME lwgdwn      -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   LCS:IRRAD EMIS:SURFACE -OBS SFCDWNC:IRRAD   -NAME lwgdwnc     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LCSC5:IRRAD EMIS:SURFACE -OBS SFCDWNC:IRRAD   -NAME lwgdwnc_cc5 -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LWS:IRRAD   LCS:IRRAD EMIS:SURFACE -OBS SFCDWN:IRRAD SFCDWNC:IRRAD -NAME lwgdwncf      -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LWS:IRRAD LCSC5:IRRAD EMIS:SURFACE -OBS SFCDWN:IRRAD SFCDWNC:IRRAD -NAME lwgdwncf_cc5  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT SFCEM:IRRAD LWS:IRRAD -OBS SFCUP:IRRAD SFCDWN:IRRAD                -NAME lwgnet        -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT SFCEM:IRRAD   LCS:IRRAD -OBS SFCUPC:IRRAD SFCDWNC:IRRAD                        -NAME lwgnetc       -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT SFCEM:IRRAD LCSC5:IRRAD -OBS SFCUPC:IRRAD SFCDWNC:IRRAD                        -NAME lwgnetc_cc5   -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LWS:IRRAD   LCS:IRRAD -OBS SFCUPC:IRRAD SFCDWNC:IRRAD SFCUP:IRRAD SFCDWN:IRRAD -NAME lwgnetcf      -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LWS:IRRAD LCSC5:IRRAD -OBS SFCUPC:IRRAD SFCDWNC:IRRAD SFCUP:IRRAD SFCDWN:IRRAD -NAME lwgnetcf_cc5  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT SFCEM:IRRAD EMIS:SURFACE LWS:IRRAD -OBS SFCUP:IRRAD                -NAME lwgup     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT SFCEM:IRRAD EMIS:SURFACE   LCS:IRRAD -OBS SFCUPC:IRRAD                   -NAME lwgupc      -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT SFCEM:IRRAD EMIS:SURFACE LCSC5:IRRAD -OBS SFCUPC:IRRAD                   -NAME lwgupc_cc5  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LWS:IRRAD   LCS:IRRAD EMIS:SURFACE -OBS SFCUP:IRRAD SFCUPC:IRRAD         -NAME lwgupcf     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LWS:IRRAD LCSC5:IRRAD EMIS:SURFACE -OBS SFCUP:IRRAD SFCUPC:IRRAD         -NAME lwgupcf_cc5 -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1


# Radiation: Net
# --------------
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME radnetg  -EXPID $expid -EXPORT RADSRF:RADIATION       -OBS RSRS:SOLAR SFCUP:IRRAD SFCDWN:IRRAD -OUTPUT $output -DEBUG $debug -SEASON $seasons "                  ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME radnetgc -EXPID $expid -EXPORT RSCS:SOLAR FLNSC:IRRAD -OBS SLRSFC:SOLAR ALBEDO:SOLAR SFCUPC:IRRAD SFCDWNC:IRRAD -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME nettoa   -EXPID $expid -EXPORT RSR:SOLAR OLR:IRRAD    -OBS RSR:SOLAR OLR:IRRAD -OUTPUT $output -DEBUG $debug -SEASON $seasons "                                  ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME nettoac      -EXPID $expid -EXPORT RSC:SOLAR   OLC:IRRAD  -OBS RSC:SOLAR   OLC:IRRAD -OUTPUT $output -DEBUG $debug -SEASON $seasons "                                  ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME nettoac_cc5  -EXPID $expid -EXPORT RSC:SOLAR OLCC5:IRRAD  -OBS RSC:SOLAR OLCC5:IRRAD -OUTPUT $output -DEBUG $debug -SEASON $seasons "                                  ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1


# Aerosols:
# ---------
# ---tavg2d_aer_x---
  setenv LONSENV "-180 180"
  set INFO  = "-SEASON $seasons -OUTPUT $output -DEBUG $debug "
# Total:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME TOTEXTTAU   -EXPID $expid -EXPORT TOTEXTTAU:GOCART   -ALT_EXPORT TOTEXTTAU:GOCART2G   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME TOTSCATAU   -EXPID $expid -EXPORT TOTSCATAU:GOCART   -ALT_EXPORT TOTSCATAU:GOCART2G   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME TOTANGSTR   -EXPID $expid -EXPORT TOTANGSTR:GOCART   -ALT_EXPORT TOTANGSTR:GOCART2G   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME TOTSTEXTTAU -EXPID $expid -EXPORT TOTSTEXTTAU:GOCART -ALT_EXPORT TOTSTEXTTAU:GOCART2G -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME TOTSTSCATAU -EXPID $expid -EXPORT TOTSTSCATAU:GOCART -ALT_EXPORT TOTSTSCATAU:GOCART2G -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME PM25        -EXPID $expid -EXPORT PM25:GOCART        -ALT_EXPORT PM25:GOCART2G        -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME PM          -EXPID $expid -EXPORT PM:GOCART          -ALT_EXPORT PM:GOCART2G          -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Dust:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUEM001     -EXPID $expid -EXPORT DUEM001:GOCART     -ALT_EXPORT DUEM:DU:001   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUEM002     -EXPID $expid -EXPORT DUEM002:GOCART     -ALT_EXPORT DUEM:DU:002   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUEM003     -EXPID $expid -EXPORT DUEM003:GOCART     -ALT_EXPORT DUEM:DU:003   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUEM004     -EXPID $expid -EXPORT DUEM004:GOCART     -ALT_EXPORT DUEM:DU:004   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUEM005     -EXPID $expid -EXPORT DUEM005:GOCART     -ALT_EXPORT DUEM:DU:005   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSD001     -EXPID $expid -EXPORT DUSD001:GOCART     -ALT_EXPORT DUSD:DU:001   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSD002     -EXPID $expid -EXPORT DUSD002:GOCART     -ALT_EXPORT DUSD:DU:002   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSD003     -EXPID $expid -EXPORT DUSD003:GOCART     -ALT_EXPORT DUSD:DU:003   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSD004     -EXPID $expid -EXPORT DUSD004:GOCART     -ALT_EXPORT DUSD:DU:004   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSD005     -EXPID $expid -EXPORT DUSD005:GOCART     -ALT_EXPORT DUSD:DU:005   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUDP001     -EXPID $expid -EXPORT DUDP001:GOCART     -ALT_EXPORT DUDP:DU:001   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUDP002     -EXPID $expid -EXPORT DUDP002:GOCART     -ALT_EXPORT DUDP:DU:002   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUDP003     -EXPID $expid -EXPORT DUDP003:GOCART     -ALT_EXPORT DUDP:DU:003   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUDP004     -EXPID $expid -EXPORT DUDP004:GOCART     -ALT_EXPORT DUDP:DU:004   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUDP005     -EXPID $expid -EXPORT DUDP005:GOCART     -ALT_EXPORT DUDP:DU:005   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUWT001     -EXPID $expid -EXPORT DUWT001:GOCART     -ALT_EXPORT DUWT:DU:001   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUWT002     -EXPID $expid -EXPORT DUWT002:GOCART     -ALT_EXPORT DUWT:DU:002   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUWT003     -EXPID $expid -EXPORT DUWT003:GOCART     -ALT_EXPORT DUWT:DU:003   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUWT004     -EXPID $expid -EXPORT DUWT004:GOCART     -ALT_EXPORT DUWT:DU:004   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUWT005     -EXPID $expid -EXPORT DUWT005:GOCART     -ALT_EXPORT DUWT:DU:005   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSMASS     -EXPID $expid -EXPORT DUSMASS:GOCART     -ALT_EXPORT DUSMASS:DU    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUCMASS     -EXPID $expid -EXPORT DUCMASS:GOCART     -ALT_EXPORT DUCMASS:DU    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSMASS25   -EXPID $expid -EXPORT DUSMASS25:GOCART   -ALT_EXPORT DUSMASS25:DU  -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUCMASS25   -EXPID $expid -EXPORT DUCMASS25:GOCART   -ALT_EXPORT DUCMASS25:DU  -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUEXTT25    -EXPID $expid -EXPORT DUEXTT25:GOCART    -ALT_EXPORT DUEXTT25:DU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSCAT25    -EXPID $expid -EXPORT DUSCAT25:GOCART    -ALT_EXPORT DUSCAT25:DU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUEXTTAU    -EXPID $expid -EXPORT DUEXTTAU:GOCART    -ALT_EXPORT DUEXTTAU:DU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSCATAU    -EXPID $expid -EXPORT DUSCATAU:GOCART    -ALT_EXPORT DUSCATAU:DU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSTEXTTAU  -EXPID $expid -EXPORT DUSTEXTTAU:GOCART  -ALT_EXPORT DUSTEXTTAU:DU -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSTSCATAU  -EXPID $expid -EXPORT DUSTSCATAU:GOCART  -ALT_EXPORT DUSTSCATAU:DU -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUANGSTR    -EXPID $expid -EXPORT DUANGSTR:GOCART    -ALT_EXPORT DUANGSTR:DU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUEXTTFM    -EXPID $expid -EXPORT DUEXTTFM:GOCART    -ALT_EXPORT DUEXTTFM:DU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSCATFM    -EXPID $expid -EXPORT DUSCATFM:GOCART    -ALT_EXPORT DUSCATFM:DU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUFLUXU     -EXPID $expid -EXPORT DUFLUXU:GOCART     -ALT_EXPORT DUFLUXU:DU    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUFLUXV     -EXPID $expid -EXPORT DUFLUXV:GOCART     -ALT_EXPORT DUFLUXV:DU    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DUSV        -EXPID $expid -EXPORT DDU2gDT:MOIST      -ALT_EXPORT MCHEMTRI%DU::DUIM:PHYSICS -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Salt:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSEM001     -EXPID $expid -EXPORT SSEM001:GOCART     -ALT_EXPORT SSEM:SS:001   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSEM002     -EXPID $expid -EXPORT SSEM002:GOCART     -ALT_EXPORT SSEM:SS:002   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSEM003     -EXPID $expid -EXPORT SSEM003:GOCART     -ALT_EXPORT SSEM:SS:003   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSEM004     -EXPID $expid -EXPORT SSEM004:GOCART     -ALT_EXPORT SSEM:SS:004   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSEM005     -EXPID $expid -EXPORT SSEM005:GOCART     -ALT_EXPORT SSEM:SS:005   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSD001     -EXPID $expid -EXPORT SSSD001:GOCART     -ALT_EXPORT SSSD:SS:001   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSD002     -EXPID $expid -EXPORT SSSD002:GOCART     -ALT_EXPORT SSSD:SS:002   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSD003     -EXPID $expid -EXPORT SSSD003:GOCART     -ALT_EXPORT SSSD:SS:003   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSD004     -EXPID $expid -EXPORT SSSD004:GOCART     -ALT_EXPORT SSSD:SS:004   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSD005     -EXPID $expid -EXPORT SSSD005:GOCART     -ALT_EXPORT SSSD:SS:005   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSDP001     -EXPID $expid -EXPORT SSDP001:GOCART     -ALT_EXPORT SSDP:SS:001   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSDP002     -EXPID $expid -EXPORT SSDP002:GOCART     -ALT_EXPORT SSDP:SS:002   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSDP003     -EXPID $expid -EXPORT SSDP003:GOCART     -ALT_EXPORT SSDP:SS:003   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSDP004     -EXPID $expid -EXPORT SSDP004:GOCART     -ALT_EXPORT SSDP:SS:004   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSDP005     -EXPID $expid -EXPORT SSDP005:GOCART     -ALT_EXPORT SSDP:SS:005   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSWT001     -EXPID $expid -EXPORT SSWT001:GOCART     -ALT_EXPORT SSWT:SS:001   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSWT002     -EXPID $expid -EXPORT SSWT002:GOCART     -ALT_EXPORT SSWT:SS:002   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSWT003     -EXPID $expid -EXPORT SSWT003:GOCART     -ALT_EXPORT SSWT:SS:003   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSWT004     -EXPID $expid -EXPORT SSWT004:GOCART     -ALT_EXPORT SSWT:SS:004   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSWT005     -EXPID $expid -EXPORT SSWT005:GOCART     -ALT_EXPORT SSWT:SS:005   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSMASS     -EXPID $expid -EXPORT SSSMASS:GOCART     -ALT_EXPORT SSSMASS:SS    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSCMASS     -EXPID $expid -EXPORT SSCMASS:GOCART     -ALT_EXPORT SSCMASS:SS    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSMASS25   -EXPID $expid -EXPORT SSSMASS25:GOCART   -ALT_EXPORT SSSMASS25:SS  -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSCMASS25   -EXPID $expid -EXPORT SSCMASS25:GOCART   -ALT_EXPORT SSCMASS25:SS  -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSEXTT25    -EXPID $expid -EXPORT SSEXTT25:GOCART    -ALT_EXPORT SSEXTT25:SS   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSCAT25    -EXPID $expid -EXPORT SSSCAT25:GOCART    -ALT_EXPORT SSSCAT25:SS   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSEXTTAU    -EXPID $expid -EXPORT SSEXTTAU:GOCART    -ALT_EXPORT SSEXTTAU:SS   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSCATAU    -EXPID $expid -EXPORT SSSCATAU:GOCART    -ALT_EXPORT SSSCATAU:SS   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSTEXTTAU  -EXPID $expid -EXPORT SSSTEXTTAU:GOCART  -ALT_EXPORT SSSTEXTTAU:SS -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSTSCATAU  -EXPID $expid -EXPORT SSSTSCATAU:GOCART  -ALT_EXPORT SSSTSCATAU:SS -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSANGSTR    -EXPID $expid -EXPORT SSANGSTR:GOCART    -ALT_EXPORT SSANGSTR:SS   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSEXTTFM    -EXPID $expid -EXPORT SSEXTTFM:GOCART    -ALT_EXPORT SSEXTTFM:SS   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSCATFM    -EXPID $expid -EXPORT SSSCATFM:GOCART    -ALT_EXPORT SSSCATFM:SS   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSFLUXU     -EXPID $expid -EXPORT SSFLUXU:GOCART     -ALT_EXPORT SSFLUXU:SS    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSFLUXV     -EXPID $expid -EXPORT SSFLUXV:GOCART     -ALT_EXPORT SSFLUXV:SS    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SSSV        -EXPID $expid -EXPORT DSS2gDT:MOIST      -ALT_EXPORT MCHEMTRI%SS::SSIM:PHYSICS -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Sulfates:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DMSEM       -EXPID $expid -EXPORT SUEM001:GOCART     -ALT_EXPORT SUEM:SU:DMSEM -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO2EM       -EXPID $expid -EXPORT SUEM002:GOCART     -ALT_EXPORT SUEM:SU:SO2EM -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO4EM       -EXPID $expid -EXPORT SUEM003:GOCART     -ALT_EXPORT SUEM:SU:SO4EM -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME MSAEM       -EXPID $expid -EXPORT SUEM004:GOCART     -ALT_EXPORT SUEM:SU:MSAEM -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DMSDP       -EXPID $expid -EXPORT SUDP001:GOCART     -ALT_EXPORT SUDP:SU:DMSDP -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO2DP       -EXPID $expid -EXPORT SUDP002:GOCART     -ALT_EXPORT SUDP:SU:SO2DP -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO4DP       -EXPID $expid -EXPORT SUDP003:GOCART     -ALT_EXPORT SUDP:SU:SO4DP -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME MSADP       -EXPID $expid -EXPORT SUDP004:GOCART     -ALT_EXPORT SUDP:SU:MSADP -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DMSWT       -EXPID $expid -EXPORT SUWT001:GOCART     -ALT_EXPORT SUWT:SU:DMSWT -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO2WT       -EXPID $expid -EXPORT SUWT002:GOCART     -ALT_EXPORT SUWT:SU:SO2WT -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO4WT       -EXPID $expid -EXPORT SUWT003:GOCART     -ALT_EXPORT SUWT:SU:SO4WT -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME MSAWT       -EXPID $expid -EXPORT SUWT004:GOCART     -ALT_EXPORT SUWT:SU:MSAWT -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DMSSD       -EXPID $expid -EXPORT SUSD001:GOCART     -ALT_EXPORT SUSD:SU:DMSSD -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO2SD       -EXPID $expid -EXPORT SUSD002:GOCART     -ALT_EXPORT SUSD:SU:SO2SD -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO4SD       -EXPID $expid -EXPORT SUSD003:GOCART     -ALT_EXPORT SUSD:SU:SO4SD -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME MSASD       -EXPID $expid -EXPORT SUSD004:GOCART     -ALT_EXPORT SUSD:SU:MSASD -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO2SMASS    -EXPID $expid -EXPORT SO2SMASS:GOCART    -ALT_EXPORT SO2SMASS:SU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO2CMASS    -EXPID $expid -EXPORT SO2CMASS:GOCART    -ALT_EXPORT SO2CMASS:SU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO4SMASS    -EXPID $expid -EXPORT SO4SMASS:GOCART    -ALT_EXPORT SO4SMASS:SU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO4CMASS    -EXPID $expid -EXPORT SO4CMASS:GOCART    -ALT_EXPORT SO4CMASS:SU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DMSSMASS    -EXPID $expid -EXPORT DMSSMASS:GOCART    -ALT_EXPORT DMSSMASS:SU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME DMSCMASS    -EXPID $expid -EXPORT DMSCMASS:GOCART    -ALT_EXPORT DMSCMASS:SU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUPSO2      -EXPID $expid -EXPORT SUPSO2:GOCART      -ALT_EXPORT SUPSO2:SU     -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUPSO4G     -EXPID $expid -EXPORT SUPSO4G:GOCART     -ALT_EXPORT SUPSO4G:SU    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUPSO4AQ    -EXPID $expid -EXPORT SUPSO4AQ:GOCART    -ALT_EXPORT SUPSO4AQ:SU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUPSO4WT    -EXPID $expid -EXPORT SUPSO4WT:GOCART    -ALT_EXPORT SUPSO4WT:SU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUPMSA      -EXPID $expid -EXPORT SUPMSA:GOCART      -ALT_EXPORT SUPMSA:SU     -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUEXTTAU    -EXPID $expid -EXPORT SUEXTTAU:GOCART    -ALT_EXPORT SUEXTTAU:SU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUSCATAU    -EXPID $expid -EXPORT SUSCATAU:GOCART    -ALT_EXPORT SUSCATAU:SU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUSTEXTTAU  -EXPID $expid -EXPORT SUSTEXTTAU:GOCART  -ALT_EXPORT SUSTEXTTAU:SU -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUSTSCATAU  -EXPID $expid -EXPORT SUSTSCATAU:GOCART  -ALT_EXPORT SUSTSCATAU:SU -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUANGSTR    -EXPID $expid -EXPORT SUANGSTR:GOCART    -ALT_EXPORT SUANGSTR:SU   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO4EMAN     -EXPID $expid -EXPORT SO4EMAN:GOCART     -ALT_EXPORT SO4EMAN:SU    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO2EMAN     -EXPID $expid -EXPORT SO2EMAN:GOCART     -ALT_EXPORT SO2EMAN:SU    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO2EMBB     -EXPID $expid -EXPORT SO2EMBB:GOCART     -ALT_EXPORT SO2EMBB:SU    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO2EMVN     -EXPID $expid -EXPORT SO2EMVN:GOCART     -ALT_EXPORT SO2EMVN:SU    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SO2EMVE     -EXPID $expid -EXPORT SO2EMVE:GOCART     -ALT_EXPORT SO2EMVE:SU    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUFLUXU     -EXPID $expid -EXPORT SUFLUXU:GOCART     -ALT_EXPORT SUFLUXU:SU    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUFLUXV     -EXPID $expid -EXPORT SUFLUXV:GOCART     -ALT_EXPORT SUFLUXV:SU    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME SUSV        -EXPID $expid -EXPORT DSU2gDT:MOIST      -ALT_EXPORT MCHEMTRI%SU::SO4IM:PHYSICS -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Nitrates:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME HNO3SMASS   -EXPID $expid -EXPORT HNO3SMASS:GOCART   -ALT_EXPORT HNO3SMASS:NI  -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NH3SMASS    -EXPID $expid -EXPORT NH3SMASS:GOCART    -ALT_EXPORT NH3SMASS:NI   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NH4SMASS    -EXPID $expid -EXPORT NH4SMASS:GOCART    -ALT_EXPORT NH4SMASS:NI   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NISMASS     -EXPID $expid -EXPORT NISMASS:GOCART     -ALT_EXPORT NISMASS:NI    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NISMASS25   -EXPID $expid -EXPORT NISMASS25:GOCART   -ALT_EXPORT NISMASS25:NI  -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME HNO3CMASS   -EXPID $expid -EXPORT HNO3CMASS:GOCART   -ALT_EXPORT HNO3CMASS:NI  -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NH3CMASS    -EXPID $expid -EXPORT NH3CMASS:GOCART    -ALT_EXPORT NH3CMASS:NI   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NH4CMASS    -EXPID $expid -EXPORT NH4CMASS:GOCART    -ALT_EXPORT NH4CMASS:NI   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NICMASS     -EXPID $expid -EXPORT NICMASS:GOCART     -ALT_EXPORT NICMASS:NI    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NICMASS25   -EXPID $expid -EXPORT NICMASS25:GOCART   -ALT_EXPORT NICMASS25:NI  -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIEXTTFM    -EXPID $expid -EXPORT NIEXTTFM:GOCART    -ALT_EXPORT NIEXTTFM:NI   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NISCATFM    -EXPID $expid -EXPORT NISCATFM:GOCART    -ALT_EXPORT NISCATFM:NI   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NISCATAU    -EXPID $expid -EXPORT NISCATAU:GOCART    -ALT_EXPORT NISCATAU:NI   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIEXTTAU    -EXPID $expid -EXPORT NIEXTTAU:GOCART    -ALT_EXPORT NIEXTTAU:NI   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIANGSTR    -EXPID $expid -EXPORT NIANGSTR:GOCART    -ALT_EXPORT NIANGSTR:NI   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIPNO3AQ    -EXPID $expid -EXPORT NIPNO3AQ:GOCART    -ALT_EXPORT NIPNO3AQ:NI   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIPNH4AQ    -EXPID $expid -EXPORT NIPNH4AQ:GOCART    -ALT_EXPORT NIPNH4AQ:NI   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIPNH3AQ    -EXPID $expid -EXPORT NIPNH3AQ:GOCART    -ALT_EXPORT NIPNH3AQ:NI   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIHT001     -EXPID $expid -EXPORT NIHT001:GOCART     -ALT_EXPORT NIHT:NI:001   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIHT002     -EXPID $expid -EXPORT NIHT002:GOCART     -ALT_EXPORT NIHT:NI:002   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIHT003     -EXPID $expid -EXPORT NIHT003:GOCART     -ALT_EXPORT NIHT:NI:003   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NISD001     -EXPID $expid -EXPORT NISD001:GOCART     -ALT_EXPORT NISD:NI:001   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NISD002     -EXPID $expid -EXPORT NISD002:GOCART     -ALT_EXPORT NISD:NI:002   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NISD003     -EXPID $expid -EXPORT NISD003:GOCART     -ALT_EXPORT NISD:NI:003   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIDP001     -EXPID $expid -EXPORT NIDP001:GOCART     -ALT_EXPORT NIDP:NI:001   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIDP002     -EXPID $expid -EXPORT NIDP002:GOCART     -ALT_EXPORT NIDP:NI:002   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIDP003     -EXPID $expid -EXPORT NIDP003:GOCART     -ALT_EXPORT NIDP:NI:003   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIWT001     -EXPID $expid -EXPORT NIWT001:GOCART     -ALT_EXPORT NIWT:NI:001   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIWT002     -EXPID $expid -EXPORT NIWT002:GOCART     -ALT_EXPORT NIWT:NI:002   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIWT003     -EXPID $expid -EXPORT NIWT003:GOCART     -ALT_EXPORT NIWT:NI:003   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NH3EM       -EXPID $expid -EXPORT NH3EM:GOCART       -ALT_EXPORT NH3EM:NI      -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NH3DP       -EXPID $expid -EXPORT NH3DP:GOCART       -ALT_EXPORT NH3DP:NI      -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NH3WT       -EXPID $expid -EXPORT NH3WT:GOCART       -ALT_EXPORT NH3WT:NI      -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NH4SD       -EXPID $expid -EXPORT NH4SD:GOCART       -ALT_EXPORT NH4SD:NI      -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NH4DP       -EXPID $expid -EXPORT NH4DP:GOCART       -ALT_EXPORT NH4DP:NI      -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NH4WT       -EXPID $expid -EXPORT NH4WT:GOCART       -ALT_EXPORT NH4WT:NI      -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIFLUXU     -EXPID $expid -EXPORT NIFLUXU:GOCART     -ALT_EXPORT NIFLUXU:NI    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NIFLUXV     -EXPID $expid -EXPORT NIFLUXV:GOCART     -ALT_EXPORT NIFLUXV:NI    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NISV        -EXPID $expid -EXPORT DNI2gDT:MOIST      -ALT_EXPORT MCHEMTRI%NI::NO3an1IM:PHYSICS -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NH3SV       -EXPID $expid -EXPORT NH3SV:NI           -ALT_EXPORT MCHEMTRI%NI::NH3IM:PHYSICS    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME NH4SV       -EXPID $expid -EXPORT NH4SV:NI           -ALT_EXPORT MCHEMTRI%NI::NH4aIM:PHYSICS   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Black Carbon:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCPHOBICEM  -EXPID $expid -EXPORT BCEM001:GOCART     -ALT_EXPORT CA.bcEM:CA.bc:BCPHOBICEM -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCPHILICEM  -EXPID $expid -EXPORT BCEM002:GOCART     -ALT_EXPORT CA.bcEM:CA.bc:BCPHILICEM -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCPHOBICDP  -EXPID $expid -EXPORT BCDP001:GOCART     -ALT_EXPORT CA.bcDP:CA.bc:BCPHOBICDP -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCPHILICDP  -EXPID $expid -EXPORT BCDP002:GOCART     -ALT_EXPORT CA.bcDP:CA.bc:BCPHILICDP -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCPHOBICWT  -EXPID $expid -EXPORT BCWT001:GOCART     -ALT_EXPORT CA.bcWT:CA.bc:BCPHOBICWT -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCPHILICWT  -EXPID $expid -EXPORT BCWT002:GOCART     -ALT_EXPORT CA.bcWT:CA.bc:BCPHILICWT -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCPHOBICSD  -EXPID $expid -EXPORT BCSD001:GOCART     -ALT_EXPORT CA.bcSD:CA.bc:BCPHOBICSD -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCPHILICSD  -EXPID $expid -EXPORT BCSD002:GOCART     -ALT_EXPORT CA.bcSD:CA.bc:BCPHILICSD -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCSMASS     -EXPID $expid -EXPORT BCSMASS:GOCART     -ALT_EXPORT CA.bcSMASS:CA.bc    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCCMASS     -EXPID $expid -EXPORT BCCMASS:GOCART     -ALT_EXPORT CA.bcCMASS:CA.bc    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCEXTTAU    -EXPID $expid -EXPORT BCEXTTAU:GOCART    -ALT_EXPORT CA.bcEXTTAU:CA.bc   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCSCATAU    -EXPID $expid -EXPORT BCSCATAU:GOCART    -ALT_EXPORT CA.bcSCATAU:CA.bc   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCSTEXTTAU  -EXPID $expid -EXPORT BCSTEXTTAU:GOCART  -ALT_EXPORT CA.bcSTEXTTAU:CA.bc -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCSTSCATAU  -EXPID $expid -EXPORT BCSTSCATAU:GOCART  -ALT_EXPORT CA.bcSTSCATAU:CA.bc -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCANGSTR    -EXPID $expid -EXPORT BCANGSTR:GOCART    -ALT_EXPORT CA.bcANGSTR:CA.bc   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCPHOB2PHIL -EXPID $expid -EXPORT BCHYPHIL:GOCART    -ALT_EXPORT CA.bcHYPHIL:CA.bc   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCEMBB      -EXPID $expid -EXPORT BCEMBB:GOCART      -ALT_EXPORT CA.bcEMBB:CA.bc     -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCEMBF      -EXPID $expid -EXPORT BCEMBF:GOCART      -ALT_EXPORT CA.bcEMBF:CA.bc     -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCEMAN      -EXPID $expid -EXPORT BCEMAN:GOCART      -ALT_EXPORT CA.bcEMAN:CA.bc     -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCFLUXU     -EXPID $expid -EXPORT BCFLUXU:GOCART     -ALT_EXPORT CA.bcFLUXU:CA.bc    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCFLUXV     -EXPID $expid -EXPORT BCFLUXV:GOCART     -ALT_EXPORT CA.bcFLUXV:CA.bc    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BCSV        -EXPID $expid -EXPORT DBC2gDT:MOIST      -ALT_EXPORT MCHEMTRI%CA.bc::CA.bcphilicIM:PHYSICS -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Organic Carbon:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCPHOBICEM  -EXPID $expid -EXPORT OCEM001:GOCART     -ALT_EXPORT CA.ocEM:CA.oc:OCPHOBICEM -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCPHILICEM  -EXPID $expid -EXPORT OCEM002:GOCART     -ALT_EXPORT CA.ocEM:CA.oc:OCPHILICEM -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCPHOBICDP  -EXPID $expid -EXPORT OCDP001:GOCART     -ALT_EXPORT CA.ocDP:CA.oc:OCPHOBICDP -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCPHILICDP  -EXPID $expid -EXPORT OCDP002:GOCART     -ALT_EXPORT CA.ocDP:CA.oc:OCPHILICDP -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCPHOBICWT  -EXPID $expid -EXPORT OCWT001:GOCART     -ALT_EXPORT CA.ocWT:CA.oc:OCPHOBICWT -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCPHILICWT  -EXPID $expid -EXPORT OCWT002:GOCART     -ALT_EXPORT CA.ocWT:CA.oc:OCPHILICWT -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCPHOBICSD  -EXPID $expid -EXPORT OCSD001:GOCART     -ALT_EXPORT CA.ocSD:CA.oc:OCPHOBICSD -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCPHILICSD  -EXPID $expid -EXPORT OCSD002:GOCART     -ALT_EXPORT CA.ocSD:CA.oc:OCPHILICSD -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCSMASS     -EXPID $expid -EXPORT OCSMASS:GOCART     -ALT_EXPORT CA.ocSMASS:CA.oc    -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCCMASS     -EXPID $expid -EXPORT OCCMASS:GOCART     -ALT_EXPORT CA.ocCMASS:CA.oc    -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCEXTTAU    -EXPID $expid -EXPORT OCEXTTAU:GOCART    -ALT_EXPORT CA.ocEXTTAU:CA.oc   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCSCATAU    -EXPID $expid -EXPORT OCSCATAU:GOCART    -ALT_EXPORT CA.ocSCATAU:CA.oc   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCSTEXTTAU  -EXPID $expid -EXPORT OCSTEXTTAU:GOCART  -ALT_EXPORT CA.ocSTEXTTAU:CA.oc -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCSTSCATAU  -EXPID $expid -EXPORT OCSTSCATAU:GOCART  -ALT_EXPORT CA.ocSTSCATAU:CA.oc -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCANGSTR    -EXPID $expid -EXPORT OCANGSTR:GOCART    -ALT_EXPORT CA.ocANGSTR:CA.oc   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCPHOB2PHIL -EXPID $expid -EXPORT OCHYPHIL:GOCART    -ALT_EXPORT CA.ocHYPHIL:CA.oc   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCEMBB      -EXPID $expid -EXPORT OCEMBB:GOCART      -ALT_EXPORT CA.ocEMBB:CA.oc     -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCEMBF      -EXPID $expid -EXPORT OCEMBF:GOCART      -ALT_EXPORT CA.ocEMBF:CA.oc     -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCEMAN      -EXPID $expid -EXPORT OCEMAN:GOCART      -ALT_EXPORT CA.ocEMAN:CA.oc     -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCEMBG      -EXPID $expid -EXPORT OCEMBG:GOCART      -ALT_EXPORT CA.ocEMBG:CA.oc     -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCPSOA      -EXPID $expid -EXPORT OCPSOA:GOCART      -ALT_EXPORT CA.ocPSOA:CA.oc     -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCFLUXU     -EXPID $expid -EXPORT OCFLUXU:GOCART     -ALT_EXPORT CA.ocFLUXU:CA.oc    -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCFLUXV     -EXPID $expid -EXPORT OCFLUXV:GOCART     -ALT_EXPORT CA.ocFLUXV:CA.oc    -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME OCSV        -EXPID $expid -EXPORT DOC2gDT:MOIST      -ALT_EXPORT MCHEMTRI%CA.oc::CA.ocphilicIM:PHYSICS -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Brown Carbon:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRPHOBICEM  -EXPID $expid -EXPORT BREM001:GOCART     -ALT_EXPORT CA.brEM:CA.br:BRPHOBICEM -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRPHILICEM  -EXPID $expid -EXPORT BREM002:GOCART     -ALT_EXPORT CA.brEM:CA.br:BRPHILICEM -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRPHOBICDP  -EXPID $expid -EXPORT BRDP001:GOCART     -ALT_EXPORT CA.brDP:CA.br:BRPHOBICDP -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRPHILICDP  -EXPID $expid -EXPORT BRDP002:GOCART     -ALT_EXPORT CA.brDP:CA.br:BRPHILICDP -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRPHOBICWT  -EXPID $expid -EXPORT BRWT001:GOCART     -ALT_EXPORT CA.brWT:CA.br:BRPHOBICWT -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRPHILICWT  -EXPID $expid -EXPORT BRWT002:GOCART     -ALT_EXPORT CA.brWT:CA.br:BRPHILICWT -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRPHOBICSD  -EXPID $expid -EXPORT BRSD001:GOCART     -ALT_EXPORT CA.brSD:CA.br:BRPHOBICSD -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRPHILICSD  -EXPID $expid -EXPORT BRSD002:GOCART     -ALT_EXPORT CA.brSD:CA.br:BRPHILICSD -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRSMASS     -EXPID $expid -EXPORT BRSMASS:GOCART     -ALT_EXPORT CA.brSMASS:CA.br    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRCMASS     -EXPID $expid -EXPORT BRCMASS:GOCART     -ALT_EXPORT CA.brCMASS:CA.br    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BREXTTAU    -EXPID $expid -EXPORT BREXTTAU:GOCART    -ALT_EXPORT CA.brEXTTAU:CA.br   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRSCATAU    -EXPID $expid -EXPORT BRCATTAU:GOCART    -ALT_EXPORT CA.brSCATAU:CA.br   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRSTEXTTAU  -EXPID $expid -EXPORT BRSTEXTTAU:GOCART  -ALT_EXPORT CA.brSTEXTTAU:CA.br -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRSTSCATAU  -EXPID $expid -EXPORT BRSTSCATAU:GOCART  -ALT_EXPORT CA.brSTSCATAU:CA.br -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRANGSTR    -EXPID $expid -EXPORT BRANGSTR:GOCART    -ALT_EXPORT CA.brANGSTR:CA.br   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRPHOB2PHIL -EXPID $expid -EXPORT BRHYPHIL:GOCART    -ALT_EXPORT CA.brHYPHIL:CA.br   -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BREMBB      -EXPID $expid -EXPORT BREMBB:GOCART      -ALT_EXPORT CA.brEMBB:CA.br     -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BREMBF      -EXPID $expid -EXPORT BREMBF:GOCART      -ALT_EXPORT CA.brEMBF:CA.br     -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BREMAN      -EXPID $expid -EXPORT BREMAN:GOCART      -ALT_EXPORT CA.brEMAN:CA.br     -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRPSOA      -EXPID $expid -EXPORT BRPSOA:GOCART      -ALT_EXPORT CA.brPSOA:CA.br     -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRFLUXU     -EXPID $expid -EXPORT BRFLUXU:GOCART     -ALT_EXPORT CA.brFLUXU:CA.br    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRFLUXV     -EXPID $expid -EXPORT BRFLUXV:GOCART     -ALT_EXPORT CA.brFLUXV:CA.br    -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot_2G -NAME BRSV        -EXPID $expid -EXPORT DBRC2gDT:MOIST     -ALT_EXPORT MCHEMTRI%CA.br::CA.brphilicIM:PHYSICS -MATH LOG $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# ---tavg3d_aer_p---
  setenv LONSENV "0 360"
  set INFO  = "-SEASON $seasons -OUTPUT $output -DEBUG $debug "
# Dust: 
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DUMASS:DU       -ALIAS DU  -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Salt: 
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT SSMASS:SS       -ALIAS SS  -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Sulfates: 
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT SO2:SU          -ALIAS SO2 -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT SO4:SU          -ALIAS SO4 -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Nitrates:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT NH3MASS:NI      -ALIAS NH3 -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT NH4MASS:NI      -ALIAS NH4 -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT NIMASS:NI       -ALIAS NI  -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Black Carbon:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT CA.bcMASS:CA.bc -ALIAS BC  -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Organic Carbon:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT CA.ocMASS:CA.oc -ALIAS OC  -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Brown Carbon:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT CA.brMASS:CA.br -ALIAS BR  -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Corbon Monoxide:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT GOCART::CO:GOCART    -ALIAS CO       -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
# Volatile Organic Compound:
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT ACHEM::VOC:ACHEM     -ALIAS VOC      -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT ACHEM::VOCbiob:ACHEM -ALIAS VOCbiob  -PTOP 30 10:L $INFO " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Experiment Comparison Plots
# ---------------------------
  setenv LONSENV "0 360"
if( $MAKE_LIST == TRUE | "$CMPEXP" != "NULL" ) then

# Surface/2-D Diagnostics
# -----------------------
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT TROPP_BLENDED:AGCM        -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT         TROPQ:AGCM        -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT         TROPT:AGCM        -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT            TS:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT            Z0:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           Z0H:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT          EMIS:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT          VENT:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT         SPEED:DYN         -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT            US:DYN         -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT            VS:DYN         -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT        SNOMAS:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT        TSLAND:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           LAI:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           GRN:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT          EVAP:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           T2M:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           Q2M:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT            QS:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT         UU10M:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT          U10M:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT          V10M:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT          U10N:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT          V10N:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           THAT:SURFACE    -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           QHAT:SURFACE    -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           WET1:SURFACE    -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           CLDLO:SOLAR     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           CLDMD:SOLAR     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           CLDHI:SOLAR     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           CLDTT:SOLAR     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           ZPBL:TURBULENCE -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           DMDT:PHYSICS    -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           TAULO:SOLAR     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           TAUMD:SOLAR     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           TAUHI:SOLAR     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           TAUTT:SOLAR     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           USTAR:SURFACE   -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           USTARW:SURFACE  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Dynamics Diagnostics
# --------------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDTDYN:DYN    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDTDYN:DYN    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDTDYN:DYN    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQVDTDYN:DYN    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"     ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    OMEGA:DYN    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"     ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DMDTDYN:DYN  DMDTANA:DYN  DMDT:PHYSICS  -NAME DMDTDYNANAPHY  -LEVEL 0" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DMDTDYN:DYN  DMDTANA:DYN                -NAME DMDTDYNANA     -LEVEL 0" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DMDTDYN:DYN                                                  -LEVEL 0" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
 
      set LEVS = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300 250 200 150 100 70 50 30 20 10 7 5 3 1 0.4'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DUDTDYN:DYN -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DVDTDYN:DYN -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDTDYN:DYN -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQVDTDYN:DYN -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    OMEGA:DYN -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

# Moist Processes Diagnostics
# ---------------------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT FCLD:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DUDT:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DVDT:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT TIM:PHYSICS     -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQDT:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQLDT:MOIST     -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQIDT:MOIST     -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQADT:MOIST     -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DTDTFRIC:MOIST  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QCTOT:AGCM      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QGTOT:AGCM      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QITOT:AGCM      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QLTOT:AGCM      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QRTOT:AGCM      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QSTOT:AGCM      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QG:MOIST        -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QI:MOIST        -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QL:MOIST        -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QR:MOIST        -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QS:MOIST        -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RL:MOIST        -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RI:MOIST        -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QLLS:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QLCN:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QILS:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QICN:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT CLLS:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT CLCN:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QGRAUPEL:MOIST  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QRAIN:MOIST     -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QSNOW:MOIST     -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT FCLD:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT CNV_MF0:MOIST   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT CNV_MFD:MOIST   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT CNV_MFC:MOIST   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT REV_CN:MOIST    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT REV_AN:MOIST    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT REV_LS:MOIST    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RSU_CN:MOIST    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RSU_AN:MOIST    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RSU_LS:MOIST    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT MUPDP:MOIST    -ALIAS MUPDP   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT MDNDP:MOIST    -ALIAS MDNDP   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT MUPMD:MOIST    -ALIAS MUPMD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT MUPSH:MOIST    -ALIAS MUPSH   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT MFD_SC:MOIST   -ALIAS MFDSC   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT UMF_SC:MOIST   -ALIAS UMFSC   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DCM_SC:MOIST   -ALIAS DCMSC   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT ENTR_DP:MOIST  -ALIAS ENTRDP  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT ENTR_MD:MOIST  -ALIAS ENTRMD  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT ENTR_SH:MOIST  -ALIAS ENTRSH  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT ENTR_SC:MOIST  -ALIAS ENTRSC  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDT_micro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQVDT_micro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQLDT_micro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQIDT_micro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQADT_micro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQRDT_micro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQSDT_micro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQGDT_micro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDT_macro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQVDT_macro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQLDT_macro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQIDT_macro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQADT_macro:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     DTDT_DC:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    DQVDT_DC:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    DQLDT_DC:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    DQIDT_DC:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    DQADT_DC:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     DTDT_SC:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    DQVDT_SC:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    DQLDT_SC:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    DQIDT_SC:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    DQADT_SC:MOIST -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      set LEVS = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300 250 200 150 100 70 50 30 20 10 7 5 3 1 0.4'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DUDT:MOIST     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DVDT:MOIST     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  TIM:PHYSICS   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQDT:MOIST     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQLDT:MOIST    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQIDT:MOIST    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQADT:MOIST    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DTDTFRIC:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QCTOT:AGCM     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QGTOT:AGCM     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QITOT:AGCM     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QLTOT:AGCM     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QRTOT:AGCM     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QSTOT:AGCM     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QG:MOIST       -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QI:MOIST       -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QL:MOIST       -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QR:MOIST       -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QS:MOIST       -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QLLS:MOIST     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QLCN:MOIST     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QILS:MOIST     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QICN:MOIST     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT CLLS:MOIST     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT CLCN:MOIST     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QGRAUPEL:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QRAIN:MOIST    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QSNOW:MOIST    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RL:MOIST       -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RI:MOIST       -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    FCLD:MOIST  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT CNV_MF0:MOIST  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT CNV_MFD:MOIST  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT CNV_MFC:MOIST  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT REV_CN:MOIST   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT REV_AN:MOIST   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT REV_LS:MOIST   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RSU_CN:MOIST   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RSU_AN:MOIST   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RSU_LS:MOIST   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT MUPDP:MOIST    -NAME MUPDP   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT MDNDP:MOIST    -NAME MDNDP   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT MUPMD:MOIST    -NAME MUPMD   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT MUPSH:MOIST    -NAME MUPSH   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT MFD_SC:MOIST   -NAME MFDSC   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT UMF_SC:MOIST   -NAME UMFSC   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DCM_SC:MOIST   -NAME DCMSC   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT ENTR_DP:MOIST  -NAME ENTRDP  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT ENTR_MD:MOIST  -NAME ENTRMD  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT ENTR_SH:MOIST  -NAME ENTRSH  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT ENTR_SC:MOIST  -NAME ENTRSC  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDT_micro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQVDT_micro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQLDT_micro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQIDT_micro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQADT_micro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQRDT_micro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQSDT_micro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQGDT_micro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDT_macro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQVDT_macro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQLDT_macro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQIDT_macro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQADT_macro:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     DTDT_DC:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    DQVDT_DC:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    DQLDT_DC:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    DQIDT_DC:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    DQADT_DC:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     DTDT_SC:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    DQVDT_SC:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    DQLDT_SC:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    DQIDT_SC:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    DQADT_SC:MOIST -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      end

# Turbulence Diagnostics
# ----------------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      UIT:PHYSICS    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      VIT:PHYSICS    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      TIT:PHYSICS    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     QVIT:PHYSICS    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     KM:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     KH:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT   KMLS:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT   KHLS:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  KHSFC:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  KHRAD:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    EKH:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    EKM:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     RI:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"  ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT INTDIS:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT TOPDIS:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 300" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      set LEVS = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     KM:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     KH:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT   KMLS:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT   KHLS:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  KHSFC:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  KHRAD:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    EKH:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    EKM:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     RI:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT INTDIS:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT TOPDIS:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    UIT:PHYSICS    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    VIT:PHYSICS    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    TIT:PHYSICS    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT   QVIT:PHYSICS    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

# Gravity Wave Drag Diagnostics
# -----------------------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT:GWD       -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT:GWD       -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT TTMGW:GWD       -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT_BKG:GWD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT_BKG:GWD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDT_BKG:GWD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT_ORO:GWD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT_ORO:GWD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDT_ORO:GWD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      set LEVS = '400 300 200 100 50 10 5 2 1 .4 .2 .1 .04 .02'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DUDT:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DVDT:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     TTMGW:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DUDT_BKG:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DVDT_BKG:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDT_BKG:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DUDT_ORO:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DVDT_ORO:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDT_ORO:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

# Radiation Diagnostics
# ---------------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RADLW:RADIATION -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RADSW:RADIATION -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      set LEVS = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300 250 200 150 100 70 50 30 20 10 7 5 3 1 0.4'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RADLW:RADIATION -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RADSW:RADIATION -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  OLA:IRRAD    OLC:IRRAD  -NAME OLRCAF    -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  LCS:IRRAD    LAS:IRRAD  -NAME LWGNETCAF -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  RSR:SOLAR  RSRNA:SOLAR  -NAME SWTNETAF  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  RSC:SOLAR  RSCNA:SOLAR  -NAME SWTNETCAF -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT RSRS:SOLAR RSRSNA:SOLAR  -NAME SWGNETAF  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT RSCS:SOLAR RSCSNA:SOLAR  -NAME SWGNETCAF -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Analysis Diagnostics
# --------------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT_ANA:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDT_ANA:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT_ANA:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQVDT_ANA:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"            ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQVDT_CON:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"            ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DUDT:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DVDT:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DTDT:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     DQVDT:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"            ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT_ANA:AGCM  -STAT STD  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDT_ANA:AGCM  -STAT STD  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT_ANA:AGCM  -STAT STD  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQVDT_ANA:AGCM  -STAT STD  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"            ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DUDT:AGCM  -STAT STD  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DVDT:AGCM  -STAT STD  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DTDT:AGCM  -STAT STD  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     DQVDT:AGCM  -STAT STD  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"            ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT_ANA:AGCM  -STAT RMS  -NAME RMS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDT_ANA:AGCM  -STAT RMS  -NAME RMS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT_ANA:AGCM  -STAT RMS  -NAME RMS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQVDT_ANA:AGCM  -STAT RMS  -NAME RMS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"            ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DUDT:AGCM  -STAT RMS  -NAME RMS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DVDT:AGCM  -STAT RMS  -NAME RMS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DTDT:AGCM  -STAT RMS  -NAME RMS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     DQVDT:AGCM  -STAT RMS  -NAME RMS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"            ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT_ANA:AGCM  -STAT BIAS  -NAME BIAS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDT_ANA:AGCM  -STAT BIAS  -NAME BIAS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT_ANA:AGCM  -STAT BIAS  -NAME BIAS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQVDT_ANA:AGCM  -STAT BIAS  -NAME BIAS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"            ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DUDT:AGCM  -STAT BIAS  -NAME BIAS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DVDT:AGCM  -STAT BIAS  -NAME BIAS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DTDT:AGCM  -STAT BIAS  -NAME BIAS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     DQVDT:AGCM  -STAT BIAS  -NAME BIAS  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"            ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT     DMDTANA:DYN  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DPSDT_CON:AGCM  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT DQVDTANAINT:DYN  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT     DMDTANA:DYN  -STAT STD             -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT     DMDTANA:DYN  -STAT BIAS -NAME BIAS -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT     DMDTANA:DYN  -STAT RMS  -NAME RMS  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT DQVDTANAINT:DYN  -STAT STD             -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT DQVDTANAINT:DYN  -STAT BIAS -NAME BIAS -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT DQVDTANAINT:DYN  -STAT RMS  -NAME RMS  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      set LEVS = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300 250 200 150 100 70 50 30 20 10 7 5 3 1 0.4'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DUDT_ANA:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DVDT_ANA:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDT_ANA:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQVDT_ANA:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQVDT_CON:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DUDT:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DVDT:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DTDT:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     DQVDT:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DUDT_ANA:AGCM  -STAT STD  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DVDT_ANA:AGCM  -STAT STD  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDT_ANA:AGCM  -STAT STD  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQVDT_ANA:AGCM  -STAT STD  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DUDT:AGCM  -STAT STD  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DVDT:AGCM  -STAT STD  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DTDT:AGCM  -STAT STD  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     DQVDT:AGCM  -STAT STD  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DUDT_ANA:AGCM  -STAT RMS -NAME RMS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DVDT_ANA:AGCM  -STAT RMS -NAME RMS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDT_ANA:AGCM  -STAT RMS -NAME RMS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQVDT_ANA:AGCM  -STAT RMS -NAME RMS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DUDT:AGCM  -STAT RMS -NAME RMS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DVDT:AGCM  -STAT RMS -NAME RMS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DTDT:AGCM  -STAT RMS -NAME RMS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     DQVDT:AGCM  -STAT RMS -NAME RMS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DUDT_ANA:AGCM  -STAT BIAS -NAME BIAS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DVDT_ANA:AGCM  -STAT BIAS -NAME BIAS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDT_ANA:AGCM  -STAT BIAS -NAME BIAS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQVDT_ANA:AGCM  -STAT BIAS -NAME BIAS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DUDT:AGCM  -STAT BIAS -NAME BIAS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DVDT:AGCM  -STAT BIAS -NAME BIAS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DTDT:AGCM  -STAT BIAS -NAME BIAS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     DQVDT:AGCM  -STAT BIAS -NAME BIAS  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

# Total Tendencies
# ----------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT:MOIST   UIT:PHYSICS DUDT:GWD                                              -NAME DUDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  TIM:PHYSICS  TIT:PHYSICS TTMGW:GWD RADLW:RADIATION RADSW:RADIATION             -NAME DTDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT                                     RADLW:RADIATION RADSW:RADIATION             -NAME DTDTRAD -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT:MOIST   VIT:PHYSICS DVDT:GWD                                              -NAME DVDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10 0.1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DQDT:MOIST  QVIT:PHYSICS                                                       -NAME DQDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"     ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT:MOIST   UIT:PHYSICS DUDT:GWD                                  DUDTDYN:DYN   DUDT_ANA:AGCM:OPT -NAME DUDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  TIM:PHYSICS  TIT:PHYSICS TTMGW:GWD RADLW:RADIATION RADSW:RADIATION DTDTDYN:DYN   DTDT_ANA:AGCM:OPT -NAME DTDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT:MOIST   VIT:PHYSICS DVDT:GWD                                  DVDTDYN:DYN   DVDT_ANA:AGCM:OPT -NAME DVDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10 0.1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DQDT:MOIST  QVIT:PHYSICS                                           DQVDTDYN:DYN DQVDT_ANA:AGCM:OPT -NAME DQDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"     ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      set LEVS = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300 250 200 150 100 70 50 30 20 10 7 5 3 1 0.4'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DUDT:MOIST  UIT:PHYSICS DUDT:GWD                                               -NAME DUDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DVDT:MOIST  VIT:PHYSICS DVDT:GWD                                               -NAME DVDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DQDT:MOIST QVIT:PHYSICS                                                        -NAME DQDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  TIM:PHYSICS  TIT:PHYSICS TTMGW:GWD RADLW:RADIATION RADSW:RADIATION             -NAME DTDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT                                     RADLW:RADIATION RADSW:RADIATION             -NAME DTDTRAD -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DUDT:MOIST  UIT:PHYSICS DUDT:GWD                                   DUDTDYN:DYN  DUDT_ANA:AGCM:OPT -NAME DUDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DVDT:MOIST  VIT:PHYSICS DVDT:GWD                                   DVDTDYN:DYN  DVDT_ANA:AGCM:OPT -NAME DVDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DQDT:MOIST QVIT:PHYSICS                                           DQVDTDYN:DYN DQVDT_ANA:AGCM:OPT -NAME DQDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  TIM:PHYSICS  TIT:PHYSICS TTMGW:GWD RADLW:RADIATION RADSW:RADIATION DTDTDYN:DYN  DTDT_ANA:AGCM:OPT -NAME DTDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

# End Experiment Comparison Plots
# -------------------------------
endif

#######################################################################################

set  FOUND = "TRUE"
if( $FOUND == FALSE ) then

#######################################################################################
#  User-Specified 2-D Plots that Match Existing Cases (eg., -type 2 -plots OLR:IRRAD )
#######################################################################################

echo " "
echo "Starting TEST for Pre-Existing plots ..."

set EXPORT = `echo $plot | cut -d: -f1`
set GC     = `echo $plot | cut -d: -f2`
set LEV    = `echo $plot | cut -d: -f3`

echo " "
echo "  PLOT: $plot"
echo "EXPORT: $EXPORT"
echo "    GC: $GC"
echo "   LEV: $LEV"
echo " "

# Find Existing Command to Execute for $plot in the form: EXPORT:GC<:LEV>
# -----------------------------------------------------------------------
# DONE
if( $plot =~ *:* & $FOUND == FALSE ) then
    set numlines = `wc -l $GEOSUTIL/plots/portrait.script | cut -d' ' -f1`
    @ m  = 1
    while( $m <= $numlines )
      set   line  = `awk -v ln=$m '{if (NR==ln) print $0}' $GEOSUTIL/plots/portrait.script`
      if( "$line" == "# DONE") then
          @ m  = $numlines
      endif
          set commands = ''
      if( .$LEV == . ) then
          set commands = `echo $line | grep ${EXPORT}:${GC}`
      else
          if( $LEV != '' & $LEV != 'Z' & $LEV != 'z' ) then 
          set commands = `echo $line | grep ${EXPORT}:${GC} | grep $LEV`
          endif
      endif
      set num = $#commands
        @ n = 2
      set dum = '$grads'
      while( $n <= $num )
         set   command   =  $commands[$n]
         if( "$command" != '$grads' ) set dum = "$dum $command"
         if( "$command" == '$grads' | $n == $num ) then
          /bin/rm -f command.file
          touch      command.file
          echo  \#\!/bin/tcsh -f            >> command.file
          echo "set LEV     = $LEV"         >> command.file
          echo "set grads   = $grads"       >> command.file
          echo "set expid   = $expid"       >> command.file
          echo "set output  = $output"      >> command.file
          echo "set debug   = $debug"       >> command.file
          echo "set batch   = $batch"       >> command.file
          echo 'set seasons = "'$seasons'"' >> command.file
          echo "$dum"                       >> command.file
          chmod +x command.file
          echo " "
          echo "Issuing command.file: ${n}"
          echo "---------------------"
          cat command.file
          echo " "
            ./command.file
          set dum = '$grads'
         endif
      @ n = $n + 1
      end
    @ m = $m + 1
    end
endif

#######################################################################################

endif

#######################################################################################
#               Experiment Comparison Plots that are NOT Pre-Existing
#######################################################################################


set EXPORT0 = `echo $plot | sed 's/::/@@/g' | cut -d: -f1 | sed 's/@@/::/g'`
set GC0     = `echo $plot | sed 's/::/@@/g' | cut -d: -f2 | sed 's/@@/::/g'`
set LEV0    = `echo $plot | sed 's/::/@@/g' | cut -d: -f3 | sed 's/@@/::/g'`

if( $MAKE_LIST == FALSE ) then
echo " "
echo "Starting TEST for NON Pre-Existing Comparison Plots ..."
echo " "
endif

if( $MAKE_LIST == TRUE | "$CMPEXP" != "NULL" ) then

        if( -e $homdir/HISTORY.rc ) then
          set EXPORTS = `$GEOSUTIL/plots/get_exports  $homdir/HISTORY.rc  portrait.script`
          foreach pair ($EXPORTS)
             set EXPORT   = `echo $pair | sed 's/::/@@/g' | cut -d: -f1 | sed 's/@@/::/g'`
             set GC       = `echo $pair | sed 's/::/@@/g' | cut -d: -f2 | sed 's/@@/::/g'`
             set LEV      = ''
             set command  = `grep ${EXPORT}:${GC} $GEOSUTIL/plots/portrait.script`
             set numplots =  $#command

             if( "$numplots" == "0" ) then
                  if( $MAKE_LIST == TRUE ) then
                     if( plot == $plotname.$n ) $grads $batch -p -c "run gencmp(z) -EXPID $expid -EXPORT ${EXPORT}:${GC} -OUTPUT ${output}/misc -DEBUG $debug -SEASON $seasons "
                  endif
                  if( $MAKE_LIST == FALSE ) then
                     if( $plot == $plotname.$n ) then
                         $grads     -b -p -c "run getzdim ${EXPORT} ${GC} $source" &
                         wait
                         set NLEVS = `cat ${EXPORT}:${GC}:NLEVS.txt`
                         /bin/rm       -f ${EXPORT}:${GC}:NLEVS.txt

                         if( $NLEVS == 1 ) then 
                             echo "Issuing gencmp for: $plotname.$n ${EXPORT}:${GC}  NLEVS: $NLEVS"
                             echo "------------------"
                             $grads $batch -p -c "run gencmp  -EXPID $expid -EXPORT ${EXPORT}:${GC} -OUTPUT ${output}/misc -DEBUG $debug -SEASON $seasons "
                         else
                             echo "Issuing gencmpz for: $plotname.$n ${EXPORT}:${GC}  NLEVS: $NLEVS"
                             echo "-------------------"
                             $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT ${EXPORT}:${GC} -OUTPUT ${output}/misc -DEBUG $debug -SEASON $seasons "
                         endif
                     endif
                     if( .$EXPORT == .$EXPORT0 & .$GC0 == .$GC ) then
                         $grads     -b -p -c "run getzdim ${EXPORT} ${GC} $source" &
                         wait
                         set NLEVS = `cat ${EXPORT}:${GC}:NLEVS.txt`
                         /bin/rm       -f ${EXPORT}:${GC}:NLEVS.txt

                         if( $NLEVS == 1 ) then 
                             echo "Issuing gencmp for: $plotname.$n ${EXPORT}:${GC}  NLEVS: $NLEVS"
                             echo "------------------"
                             $grads $batch -p -c "run gencmp  -EXPID $expid -EXPORT ${EXPORT}:${GC} -OUTPUT ${output}/misc -DEBUG $debug -SEASON $seasons "
                             $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT ${EXPORT}:${GC} -OUTPUT ${output}/misc -DEBUG $debug -SEASON $seasons "
                         else
                             echo "Issuing gencmpz for: $plotname.$n ${EXPORT}:${GC}  NLEVS: $NLEVS"
                             echo "-------------------"
                             $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT ${EXPORT}:${GC} -OUTPUT ${output}/misc -DEBUG $debug -SEASON $seasons "
                         endif
                     endif
                  endif
                 set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
             endif
          end
        endif

endif

#######################################################################################

if( $MAKE_LIST == TRUE ) echo $plots

exit
