#!/usr/bin/env bash
# run_pipeline.sh
#
# Meta-script that orchestrates the full MERRA-2 OX pchem pipeline.
#
# For every month from 1979-02 through END_YEAR/END_MONTH the script:
#   1. Checks if a zonal mean already exists (archive or local output dir)
#   2. If not, checks if a monthly average exists (archive or local output dir)
#      → if yes, generates the zonal mean directly
#      → if no, marks the month as needing SLURM time-averaging
#   3. Submits a single SLURM job (compute_time_ave.sh) covering the full
#      range of months that need time-averaging, waits for it, then generates
#      the remaining zonal means
#   3b. Symlinks all archive zonal means into ZONAL_OUT_DIR so that
#       generate_merra2ox_species.sh has a single directory to work from
#   4. Runs generate_merra2ox_species.sh END_YYYYMM to assemble the final
#      pchem species file
#   5. Moves newly generated monthly averages and zonal means to dedicated
#      output directories, then removes the working dirs (which at that point
#      contain only symlinks)
#
# Usage:
#   ./run_pipeline.sh
#
# Configure the variables in the "Configuration" section below before running.

set -euo pipefail

# ===========================================================================
# Configuration
# ===========================================================================

END_YEAR=2017
END_MONTH=6

# Read-only archive directories (never written to by this script)
MONTHLY_ARCHIVE_DIR="/home/bmauer/noback/merra2_data/monthly_ave"   # pre-existing monthly time-averaged files
ZONAL_ARCHIVE_DIR="/home/bmauer/noback/merra2_data/monthly_zonal"       # pre-existing zonal mean files

# Input data paths passed through to sub-scripts
MODEL_BUILD_DIR="/discover/swdev/bmauer/models/geosgcm_v11.10.0/GEOSgcm/install-release"
MERRA2_DAILY_SOURCE="/discover/nobackup/projects/gmao/merra2/data/products/d5124_m2_jan10"
CMIP_DIR="/discover/nobackup/projects/gmao/bcs_shared/fvInput/ExtData/esm/tiles/v12/PCHEM"             # directory containing the CMIP input species file
LEV_SOURCE="${CMIP_DIR}/pchem.species.CMIP-5.MERRA2OX.197902-201706.z_91x72.nc4"   # file whose lev variable (float64) is copied into the output

# Working directories used during the pipeline run (deleted at the end)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MONTHLY_OUT_DIR="${SCRIPT_DIR}/monthly_files"
ZONAL_OUT_DIR="${SCRIPT_DIR}/monthly_zonal"

# Final destinations for files generated by this run (kept after cleanup)
MONTHLY_NEW_DIR="${SCRIPT_DIR}/monthly_files_new"
ZONAL_NEW_DIR="${SCRIPT_DIR}/monthly_zonal_new"

# File naming patterns
MONTHLY_PREFIX="MERRA-2.inst3_3d_asm_Nv.monthly"
ZONAL_SUFFIX="0001x0091x0072"

# ===========================================================================
# Helpers
# ===========================================================================

log() { printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

# monthly_file YYYYMM — print path if found in archive or output dir, else empty
monthly_file() {
    local yyyymm="$1"
    local name="${MONTHLY_PREFIX}.${yyyymm}.nc4"
    if [[ -f "${MONTHLY_ARCHIVE_DIR}/${name}" ]]; then
        printf '%s' "${MONTHLY_ARCHIVE_DIR}/${name}"
    elif [[ -f "${MONTHLY_OUT_DIR}/${name}" ]]; then
        printf '%s' "${MONTHLY_OUT_DIR}/${name}"
    fi
}

# zonal_file YYYYMM — print path if found in archive or output dir, else empty
zonal_file() {
    local yyyymm="$1"
    local name="${MONTHLY_PREFIX}.${yyyymm}.${ZONAL_SUFFIX}.nc4"
    if [[ -f "${ZONAL_ARCHIVE_DIR}/${name}" ]]; then
        printf '%s' "${ZONAL_ARCHIVE_DIR}/${name}"
    elif [[ -f "${ZONAL_OUT_DIR}/${name}" ]]; then
        printf '%s' "${ZONAL_OUT_DIR}/${name}"
    fi
}

# ===========================================================================
# Input validation
# ===========================================================================

[[ "${END_YEAR}"  =~ ^[0-9]{4}$   ]] || die "END_YEAR must be a 4-digit year, got '${END_YEAR}'"
[[ "${END_MONTH}" =~ ^[0-9]{1,2}$ ]] || die "END_MONTH must be a numeric month, got '${END_MONTH}'"
(( 10#$END_MONTH >= 1 && 10#$END_MONTH <= 12 )) || die "END_MONTH must be between 1 and 12"

# Pipeline always starts at 1979-02 (beginning of the CMIP file)
START_YEAR=1979
START_MONTH=2

END_YYYYMM="$(printf '%04d%02d' "$END_YEAR" "$END_MONTH")"

log "Pipeline end date: ${END_YEAR}-$(printf '%02d' "$END_MONTH")  (start fixed at 1979-02)"

mkdir -p "${MONTHLY_OUT_DIR}" "${ZONAL_OUT_DIR}"

# ===========================================================================
# Step 1 — Classify every month from 1979-02 through END_YYYYMM
# ===========================================================================

log "Step 1: Auditing required months..."

needs_slurm=()   # YYYYMM values with no monthly average anywhere
needs_zonal=()   # YYYYMM values with a monthly average but no zonal mean
satisfied=0

y=$START_YEAR
m=$START_MONTH
while :; do
    mm=$(printf '%02d' "$m")
    yyyymm="${y}${mm}"

    if [[ -n "$(zonal_file "$yyyymm")" ]]; then
        satisfied=$(( satisfied + 1 ))
    elif [[ -n "$(monthly_file "$yyyymm")" ]]; then
        needs_zonal+=("$yyyymm")
    else
        needs_slurm+=("$yyyymm")
    fi

    if (( y == END_YEAR && m == END_MONTH )); then break; fi
    if (( m == 12 )); then y=$(( y + 1 )); m=1; else m=$(( m + 1 )); fi
done

log "  Months with zonal mean already present:               ${satisfied}"
log "  Months needing zonal mean (monthly average available): ${#needs_zonal[@]}"
log "  Months needing SLURM time-averaging:                   ${#needs_slurm[@]}"

# ===========================================================================
# Step 2 — Submit a single SLURM job for all months that need time-averaging
# ===========================================================================

if (( ${#needs_slurm[@]} > 0 )); then
    first="${needs_slurm[0]}"
    last="${needs_slurm[-1]}"
    slurm_start_year="${first:0:4}"
    slurm_start_month="${first:4:2}"
    slurm_end_year="${last:0:4}"
    slurm_end_month="${last:4:2}"

    log "Step 2: Submitting SLURM job for ${first}–${last}..."
    job_id=$(sbatch --parsable \
        "${SCRIPT_DIR}/compute_time_ave.sh" \
        "$slurm_start_year" "$slurm_start_month" \
        "$slurm_end_year"   "$slurm_end_month" \
        "${MODEL_BUILD_DIR}" "${MERRA2_DAILY_SOURCE}" "${MONTHLY_OUT_DIR}")

    log "  Submitted SLURM job ID: ${job_id}"
    log "  Polling until job completes (checking every 60 s)..."

    while squeue -j "$job_id" -h 2>/dev/null | grep -q .; do
        sleep 60
    done

    exit_code=$(sacct -j "$job_id" --format=ExitCode --noheader \
        | awk -F: 'NR==1{print $1}' | tr -d ' ')
    if [[ "$exit_code" != "0" ]]; then
        die "SLURM job ${job_id} finished with exit code ${exit_code}. Aborting pipeline."
    fi
    log "  SLURM job ${job_id} completed successfully."

    # SLURM months now have monthly averages — add them to the zonal generation queue
    needs_zonal+=("${needs_slurm[@]}")
else
    log "Step 2: No months require SLURM time-averaging — skipping."
fi

# ===========================================================================
# Step 3 — Generate zonal means for all months that need them
# ===========================================================================

if (( ${#needs_zonal[@]} > 0 )); then
    log "Step 3: Generating zonal means for ${#needs_zonal[@]} month(s)..."
    for yyyymm in "${needs_zonal[@]}"; do
        monthly_src="$(monthly_file "$yyyymm")"
        if [[ -z "$monthly_src" ]]; then
            die "Monthly average for ${yyyymm} still not found after SLURM step. Aborting."
        fi
        zonal_tmp="${ZONAL_OUT_DIR}/monthly_ave.${yyyymm}.${ZONAL_SUFFIX}.nc4"
        zonal_final="${ZONAL_OUT_DIR}/${MONTHLY_PREFIX}.${yyyymm}.${ZONAL_SUFFIX}.nc4"
        log "  ${yyyymm}: ${monthly_src} -> ${zonal_final}"
        python3 "${SCRIPT_DIR}/zonal_mean_subsample_o3.py" \
            "${monthly_src}" "${zonal_tmp}"
        mv "${zonal_tmp}" "${zonal_final}"
    done
    log "  Zonal mean generation complete."
else
    log "Step 3: All zonal means already present — skipping."
fi

# ===========================================================================
# Step 3b — Symlink archive zonal means into ZONAL_OUT_DIR
#
# ZONAL_OUT_DIR is passed to generate_merra2ox_species.sh as the single
# source directory. Months whose zonal means live only in ZONAL_ARCHIVE_DIR
# are symlinked in so everything is visible from one place.
# ===========================================================================

log "Step 3b: Symlinking archive zonal means into ${ZONAL_OUT_DIR}..."
linked=0
y=$START_YEAR
m=$START_MONTH
while :; do
    mm=$(printf '%02d' "$m")
    yyyymm="${y}${mm}"
    name="${MONTHLY_PREFIX}.${yyyymm}.${ZONAL_SUFFIX}.nc4"
    archive_src="${ZONAL_ARCHIVE_DIR}/${name}"
    local_dst="${ZONAL_OUT_DIR}/${name}"

    if [[ -f "$archive_src" && ! -e "$local_dst" ]]; then
        ln -sfn "$archive_src" "$local_dst"
        linked=$(( linked + 1 ))
    fi

    if (( y == END_YEAR && m == END_MONTH )); then break; fi
    if (( m == 12 )); then y=$(( y + 1 )); m=1; else m=$(( m + 1 )); fi
done
log "  Symlinked ${linked} archive zonal mean file(s)."

# ===========================================================================
# Step 4 — Assemble pchem species file
# ===========================================================================

log "Step 4: Assembling pchem species file through ${END_YYYYMM}..."
bash "${SCRIPT_DIR}/generate_merra2ox_species.sh" "${END_YYYYMM}" "${ZONAL_OUT_DIR}" "${CMIP_DIR}" "${LEV_SOURCE}"
log "  pchem species file generation complete."

# ===========================================================================
# Step 5 — Move newly generated files to permanent directories, clean up
# ===========================================================================

log "Step 5: Moving newly generated files to permanent directories..."

mkdir -p "${MONTHLY_NEW_DIR}" "${ZONAL_NEW_DIR}"

# Move real files (not symlinks) out of the working directories
monthly_moved=0
for f in "${MONTHLY_OUT_DIR}"/*; do
    [[ -e "$f" ]] || continue          # glob miss
    if [[ -f "$f" && ! -L "$f" ]]; then
        mv "$f" "${MONTHLY_NEW_DIR}/"
        monthly_moved=$(( monthly_moved + 1 ))
    fi
done

zonal_moved=0
for f in "${ZONAL_OUT_DIR}"/*; do
    [[ -e "$f" ]] || continue          # glob miss
    if [[ -f "$f" && ! -L "$f" ]]; then
        mv "$f" "${ZONAL_NEW_DIR}/"
        zonal_moved=$(( zonal_moved + 1 ))
    fi
done

log "  Moved ${monthly_moved} new monthly average(s) to ${MONTHLY_NEW_DIR}"
log "  Moved ${zonal_moved} new zonal mean(s) to ${ZONAL_NEW_DIR}"

# Remove working directories (contain only symlinks or are empty at this point)
rm -rf "${MONTHLY_OUT_DIR}" "${ZONAL_OUT_DIR}"
log "  Removed working directories."

# ===========================================================================

log "Pipeline finished successfully."
